(() => {
  'use strict';
  const apertures = [
    {id:'plant',code:'MW-AP-01',label:'Useful plant',kicker:'Origin object',title:'One useful plant reveals the operating system.',body:'Fresh catnip joins household value, animal use, propagation, water, light, space, cost, care cadence, tools, and memory in one small object.',evidence:'Derived photographic detail from the retained household donor.',matters:'A repeatable growing method that fits the household’s actual attention and space.',next:'Test the smallest complete care loop and preserve what worked.',authority:'The household decides whether the object belongs in its life.',caption:'The origin remains deliberately small, useful, and observable.',source:'Photographic donor · derived detail'},
    {id:'household',code:'MW-AP-02',label:'Household',kicker:'Lived system',title:'The yard is an inhabited operating environment.',body:'People, animals, food, play, sensory relief, shade, water, tools, maintenance, and caregiver attention occupy the same place.',evidence:'Retained household photograph from the qualified v1.1.2 public donor.',matters:'Daily use and care burden before ornamental category or outside judgment.',next:'Map the routines and capacities the place must support before proposing change.',authority:'Observation cannot override household consent or invent household capacity.',caption:'Household Habitat keeps lived use and burden in the same record.',source:'Retained photographic donor'},
    {id:'property',code:'MW-AP-03',label:'Property',kicker:'Visible twin',title:'Overlapping conditions stay independently inspectable.',body:'Shade, water, access, fuel, habitat, labor, structures, and authority share one physical place without becoming one score.',evidence:'Retained property photograph from the qualified v1.1.2 public donor.',matters:'Natural borders, dependencies, visible edges, source quality, and what remains unknown.',next:'Attach each claim to a bounded zone or edge and retain uncertainty.',authority:'A visual interpretation is not a survey, inspection, entry right, or work authorization.',caption:'The property aperture exposes dependencies without manufacturing parcel certainty.',source:'Retained photographic donor'},
    {id:'street',code:'MW-AP-04',label:'Street',kicker:'Street Glide',title:'The public edge is read through natural borders.',body:'Curb, canopy, roof, sidewalk, driveway, utility, parcel, and work edges divide responsibility while the street remains one inhabited scene.',evidence:'Derived street-edge crop with authored, image-registered analytical marks.',matters:'Where a visible condition meets access, ownership, public responsibility, and shared effects.',next:'Read the edge, retain uncertainty, and distinguish household, neighbor, utility, and public roles.',authority:'A street observation creates no access, enforcement, ownership, or maintenance authority.',caption:'Street Glide follows the visible landscape instead of floating geometry.',source:'Derived photographic street-edge crop'},
    {id:'neighborhood',code:'MW-AP-05',label:'Neighborhood',kicker:'Shared capacity',title:'Linked conditions meet unequal capacity.',body:'Adjacent households share heat, canopy, water, access, smoke, tools, nurseries, trusted relays, and labor without becoming interchangeable units.',evidence:'Derived multi-place analytical composite from retained donor bytes.',matters:'The specific shared condition and the specific capacity gap, with household boundaries intact.',next:'Route the capacity gap to the function able to help before adding obligations.',authority:'Neighborhood context cannot become a household verdict, ranking, or reputation score.',caption:'The neighborhood aperture widens effects and resources while retaining household agency.',source:'Derived multi-place analytical composite'},
    {id:'region',code:'MW-AP-06',label:'Region',kicker:'Regional Observatory',title:'Wide context remains separate from local determination.',body:'Heat, air, wildfire, water, access, supply, labor, terrain, and public programs shape many places differently and change over time.',evidence:'Modeled regional context derived from retained photographic donors.',matters:'Signal, verified finding, capacity, completed mitigation, and time must remain distinct.',next:'Use regional context to prioritize assistance and evidence collection.',authority:'No automatic insurance denial, unrelated scoring, evacuation order, or parcel determination.',caption:'The regional aperture widens the record without manufacturing local certainty.',source:'Derived modeled regional context'},
    {id:'stewardship',code:'MW-AP-07',label:'Stewardship',kicker:'Continuity',title:'The work survives a change of hands.',body:'Evidence, rationale, authority, safe preparation, verification, held effects, and unresolved branches remain reconstructable after a role changes.',evidence:'Derived continuity contact sheet plus the current public interaction state.',matters:'Why the condition mattered, what authority existed, what was prepared, what happened, and what remains safe.',next:'Verify the result and export a trustworthy handoff.',authority:'External effects require real authority. Internal preparation and continuity do not require finding a person.',caption:'Stewardship turns the place into a durable, bounded handoff.',source:'Derived continuity contact sheet'}
  ];
  const overlays = [
    {id:'habitat',label:'Habitat',cls:'overlay-habitat'},
    {id:'shade',label:'Shade + heat',cls:'overlay-shade'},
    {id:'water',label:'Water',cls:'overlay-water'},
    {id:'fire',label:'Fire',cls:'overlay-fire'},
    {id:'air',label:'Air',cls:'overlay-air'},
    {id:'access',label:'Access',cls:'overlay-access'},
    {id:'labor',label:'Labor + tools',cls:'overlay-labor'},
    {id:'authority',label:'Authority + programs',cls:'overlay-authority'}
  ];
  const roles = [
    {id:'resident',code:'R-01',label:'Resident',body:'Reads the place through daily use, consent, cost, care load, correction, and recourse.',action:'Correct, narrow, defer, or prepare a household-safe next step.',acceptance:'The reading supports lived use without adding an unrequested burden.',handoff:'A bounded household context packet with no external effect.',layers:['habitat','shade','water']},
    {id:'nursery',code:'R-02',label:'Nursery / grower',body:'Reads what can be propagated, supplied, maintained, replaced, and supported locally.',action:'Prepare fit, timing, supply, replacement, and survival questions.',acceptance:'The plant and supply option match the place, season, and care capacity.',handoff:'A source-bounded plant and supply brief.',layers:['habitat','water','labor']},
    {id:'crew',code:'R-03',label:'Crew / steward',body:'Reads what work is authorized, accessible, safe, dependent, and verifiable.',action:'Prepare scope, access, tools, dependencies, hazards, and acceptance criteria.',acceptance:'The work can be performed within real access and authority.',handoff:'A bounded work-preparation packet, not an assignment.',layers:['access','labor','fire']},
    {id:'planner',code:'R-04',label:'Planner / program',body:'Reads where shared conditions justify resources without inventing parcel certainty.',action:'Prepare assistance eligibility questions and affected-interest review.',acceptance:'Resources reach the named capacity gap without adverse reuse.',handoff:'A purpose-limited assistance-routing record.',layers:['fire','air','authority']},
    {id:'successor',code:'R-05',label:'Successor',body:'Reads why the current state exists and what remains safe to continue.',action:'Verify sources, rationale, authority, receipts, failures, and open branches.',acceptance:'A cold successor can reconstruct the object without private oral history.',handoff:'A portable continuity packet with unresolved branches intact.',layers:['authority','access','labor']}
  ];
  const defaults = {plant:['habitat','water'],household:['habitat','shade'],property:['water','access'],street:['access','authority'],neighborhood:['shade','labor'],region:['fire','air'],stewardship:['authority','labor']};
  const state = {aperture:'plant',role:'resident',layers:new Set(defaults.plant),sceneData:{}};
  const $ = selector => document.querySelector(selector);
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function params(){return new URLSearchParams(location.search)}
  function announce(text){const region=$('#liveStatus');if(region)region.textContent=text}
  function currentAperture(){return apertures.find(item=>item.id===state.aperture)||apertures[0]}
  function currentRole(){return roles.find(item=>item.id===state.role)||roles[0]}
  function syncUrl(){const url=new URL(location.href);url.searchParams.set('aperture',state.aperture);url.searchParams.set('role',state.role);url.searchParams.set('layers',overlays.filter(o=>state.layers.has(o.id)).map(o=>o.id).join(','));history.replaceState(null,'',`${url.pathname}?${url.searchParams.toString()}${url.hash}`)}
  function hydrateFromUrl(){const p=params();if(apertures.some(a=>a.id===p.get('aperture')))state.aperture=p.get('aperture');if(roles.some(r=>r.id===p.get('role')))state.role=p.get('role');if(p.has('layers'))state.layers=new Set((p.get('layers')||'').split(',').filter(id=>overlays.some(o=>o.id===id)));else state.layers=new Set(defaults[state.aperture])}
  function buildControls(){
    $('#apertureRail').innerHTML=apertures.map(a=>`<button type="button" data-aperture="${a.id}" aria-pressed="${a.id===state.aperture}">${esc(a.label)}</button>`).join('');
    $('#overlayRail').innerHTML=overlays.map(o=>`<button type="button" data-overlay="${o.id}" aria-pressed="${state.layers.has(o.id)}">${esc(o.label)}</button>`).join('');
    $('#roleRail').innerHTML=roles.map(r=>`<button type="button" data-role="${r.id}" aria-pressed="${r.id===state.role}">${esc(r.label)}</button>`).join('');
  }
  function drawOverlays(){const datum=state.sceneData[state.aperture];const active=overlays.filter(o=>state.layers.has(o.id));const svg=$('#overlaySvg');svg.innerHTML=active.flatMap((overlay,index)=>{const paths=((datum&&datum.registration&&datum.registration[overlay.id])||[]);const labelY=28+index*24;return paths.map((d,pathIndex)=>`<path class="overlay-path ${overlay.cls}" data-overlay-shape="${overlay.id}" d="${d}" opacity="${pathIndex===0?'.94':'.63'}"></path>`).concat([`<text x="${760}" y="${labelY}" class="overlay-tag" fill="currentColor">${esc(overlay.label)}</text>`])}).join('');document.querySelectorAll('[data-overlay]').forEach(b=>b.setAttribute('aria-pressed',String(state.layers.has(b.dataset.overlay))))}
  function render(){
    const aperture=currentAperture();const role=currentRole();const datum=state.sceneData[aperture.id]||{};
    document.documentElement.dataset.aperture=aperture.id;document.documentElement.dataset.role=role.id;
    document.querySelectorAll('button[data-aperture]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.aperture===aperture.id)));
    document.querySelectorAll('button[data-role]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===role.id)));
    $('#sceneCode').textContent=aperture.code;$('#sceneClass').textContent=datum.classification||aperture.source;$('#sceneImage').src=datum.asset||`assets/${aperture.id}.webp`;$('#sceneImage').alt=`${aperture.label} aperture. ${aperture.caption}`;$('#sceneLabel').textContent=aperture.label;$('#sceneSource').textContent=aperture.source;$('#sceneCaption').textContent=aperture.caption;
    $('#apertureKicker').textContent=aperture.kicker;$('#apertureTitle').textContent=aperture.title;$('#apertureBody').textContent=aperture.body;$('#evidenceView').textContent=aperture.evidence;$('#whatMatters').textContent=aperture.matters;$('#nextAction').textContent=aperture.next;$('#authorityBoundary').textContent=aperture.authority;
    $('#roleCode').textContent=role.code;$('#roleTitle').textContent=role.label;$('#roleBody').textContent=role.body;$('#roleAction').textContent=role.action;$('#roleAcceptance').textContent=role.acceptance;$('#roleHandoff').textContent=role.handoff;
    $('#handoffMove').textContent=`${role.label}: ${role.handoff}`;
    $('#handoffLink').href=`../essential-attention/?from=manzanita-1.6.0&aperture=${encodeURIComponent(aperture.id)}&role=${encodeURIComponent(role.id)}&layers=${encodeURIComponent([...state.layers].join(','))}`;
    drawOverlays();syncUrl();
  }
  function selectAperture(id,{reset=true,notify=true}={}){if(!apertures.some(a=>a.id===id))return;state.aperture=id;if(reset)state.layers=new Set(defaults[id]);render();if(notify)announce(`${currentAperture().label} aperture selected. ${currentAperture().title}`)}
  function selectRole(id,{applyLayers=true,notify=true}={}){if(!roles.some(r=>r.id===id))return;state.role=id;if(applyLayers)state.layers=new Set(currentRole().layers);render();if(notify)announce(`${currentRole().label} seat selected. ${currentRole().action}`)}
  function toggleLayer(id){const item=overlays.find(o=>o.id===id);if(!item)return;const show=!state.layers.has(id);show?state.layers.add(id):state.layers.delete(id);render();announce(`${item.label} condition ${show?'shown':'hidden'}.`)}
  function bindGroup(container,selector,activate){container.addEventListener('keydown',event=>{if(!['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(event.key))return;const buttons=[...container.querySelectorAll(selector)];const current=buttons.indexOf(event.target.closest(selector));if(current<0)return;event.preventDefault();let next=current;if(event.key==='Home')next=0;else if(event.key==='End')next=buttons.length-1;else if(event.key==='ArrowRight'||event.key==='ArrowDown')next=(current+1)%buttons.length;else next=(current-1+buttons.length)%buttons.length;buttons[next].focus();if(activate)activate(buttons[next])})}
  function updateTheme(){const dark=document.documentElement.dataset.theme==='dark';$('#themeToggle').setAttribute('aria-pressed',String(dark));$('#themeLabel').textContent=dark?'Dark':'Light';document.querySelector('meta[name="theme-color"]').setAttribute('content',dark?'#151611':'#f1eee5')}
  async function boot(){
    state.sceneData=window.MANZANITA_SCENES||{};if(Object.keys(state.sceneData).length!==7)throw new Error('scene-data unavailable');
    hydrateFromUrl();buildControls();render();updateTheme();
    $('#apertureRail').addEventListener('click',e=>{const b=e.target.closest('[data-aperture]');if(b)selectAperture(b.dataset.aperture)});
    $('#overlayRail').addEventListener('click',e=>{const b=e.target.closest('[data-overlay]');if(b)toggleLayer(b.dataset.overlay)});
    $('#roleRail').addEventListener('click',e=>{const b=e.target.closest('[data-role]');if(b)selectRole(b.dataset.role)});
    $('#nextAperture').addEventListener('click',()=>{const i=apertures.findIndex(a=>a.id===state.aperture);selectAperture(apertures[(i+1)%apertures.length].id);$('#scene').scrollIntoView({block:'center'})});
    $('#themeToggle').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('manzanita-theme',next);updateTheme()});
    $('#printSheet').addEventListener('click',()=>window.print());
    $('#exportState').addEventListener('click',()=>{const payload={schema:'manzanita-works/public-reading@1',release:'1.6.0',aperture:state.aperture,role:state.role,layers:overlays.filter(o=>state.layers.has(o.id)).map(o=>o.id),authority:{external_effect:'none',public_projection:true}};const blob=new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`manzanita-${state.aperture}-${state.role}.json`;a.click();URL.revokeObjectURL(url);announce('The current public reading was exported locally.')});
    bindGroup($('#apertureRail'),'[data-aperture]',b=>selectAperture(b.dataset.aperture));bindGroup($('#roleRail'),'[data-role]',b=>selectRole(b.dataset.role));bindGroup($('#overlayRail'),'[data-overlay]',null);
  }
  boot().catch(error=>{console.error(error);announce('The place fabric could not load its retained scene registration.');document.documentElement.dataset.loadState='failed'});
})();
