'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const B=require('../scripts/connect.cjs'),F=require('../inputs/fixtures.cjs');
function liveFixture(){const s=F.snapshot(),past=new Date(Date.now()-1000).toISOString(),future=new Date(Date.now()+60000).toISOString();for(const c of s.candidates){for(const k of ['supply','quote','performance','environment'])Object.assign(c[k],{observed_at:past,expires_at:future});}return s;}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'request-inputs-')),file=path.join(dir,'snapshot.json');fs.writeFileSync(file,JSON.stringify(liveFixture()));return {dir,file};}
test('new tools are read-only and available through existing workspace',async()=>{const w=B.makeWorkspace({}),m=await B.call(w,'compute_input_materials',{}),r=await B.call(w,'compute_place_request',{request:F.request()});a.equal(m.materials.length,20);a.equal(r.status,'INPUTS_REQUIRED');a.equal(r.execution_authorized,false);a.ok(B.tools.filter(t=>t.name.includes('place')||t.name.includes('materials')).every(t=>t.annotations.readOnlyHint));});
test('configured file reaches same placement engine',async()=>{const t=setup();try{const w=B.makeWorkspace({placementFile:t.file}),r=await B.call(w,'compute_place_request',{request:F.request()});a.equal(r.selected.id,'ha');a.equal(r.synthetic,true);a.equal(r.execution_authorized,false);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});
test('file changes are read and stale stock is held rather than cached',async()=>{const t=setup();try{const w=B.makeWorkspace({placementFile:t.file});const before=await B.call(w,'compute_place_request',{request:F.request()});const s=liveFixture();s.candidates[1].supply.expires_at=new Date(Date.now()-500).toISOString();fs.writeFileSync(t.file,JSON.stringify(s));const after=await B.call(w,'compute_place_request',{request:F.request()});a.equal(before.selected.id,'ha');a.equal(after.selected.id,'do');}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});
test('request cannot supply arbitrary path or endpoint',async()=>{const w=B.makeWorkspace({});await a.rejects(B.call(w,'compute_place_request',{request:F.request(),path:'/secret'}));await a.rejects(B.call(w,'compute_place_request',{request:{...F.request(),url:'http://169.254.169.254'}}));await a.rejects(B.call(w,'compute_place_request',{request:{...F.request(),cache_key:{source:'untrusted'}}}));});
test('malformed input is not replaced by fixture',async()=>{const t=setup();try{const w=B.makeWorkspace({placementFile:t.file});fs.writeFileSync(t.file,'{bad');await a.rejects(B.call(w,'compute_place_request',{request:F.request()}));}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});
test('actual stdio client gets the new tool result with no shell or network step',async()=>{const t=setup();try{const p=spawn(process.execPath,[path.join(__dirname,'../scripts/connect.cjs'),'--mcp','--placement-file',t.file],{stdio:['pipe','pipe','pipe']});let out='',err='';p.stdout.on('data',s=>out+=s);p.stderr.on('data',s=>err+=s);p.stdin.end([{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25'}},{jsonrpc:'2.0',method:'notifications/initialized'},{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'compute_place_request',arguments:{request:F.request()}}}].map(JSON.stringify).join('\n')+'\n');const code=await new Promise((r,j)=>{p.on('error',j);p.on('exit',r)});a.equal(code,0,err);const lines=out.trim().split('\n').map(JSON.parse);a.equal(lines[1].result.structuredContent.selected.id,'ha');a.equal(lines[1].result.structuredContent.execution_authorized,false);}finally{fs.rmSync(t.dir,{recursive:true,force:true});}});
