'use strict';
const SAMPLE=window.CSF_SAMPLE;
const TYPES=['protocols','participants','visits','delegations','resources','bookings','source_events','mec6_assessments','model_certificates'];
const CONTRACTS={
 protocols:{required:['protocol_id','sponsor_id','version'],optional:['title','effective_from','effective_to','stage','risk_class','requirements'],key:r=>`${r.protocol_id}::${r.version}`},
 participants:{required:['participant_id','protocol_id','sponsor_id'],optional:['state','next_visit'],key:r=>r.participant_id},
 visits:{required:['visit_id','participant_id','protocol_id','protocol_version','scheduled_at'],optional:['status','room_id'],key:r=>r.visit_id},
 delegations:{required:['delegation_id','role_id','protocol_id','action'],optional:['valid_from','valid_to','status'],key:r=>r.delegation_id},
 resources:{required:['resource_id','type'],optional:['capacity','status'],key:r=>r.resource_id},
 bookings:{required:['booking_id','resource_id','protocol_id','participant_id','start_at','end_at'],optional:['role_id'],key:r=>r.booking_id},
 source_events:{required:['event_id','event_type','source_identity'],optional:['protocol_id','participant_id','protocol_version','occurred_at','due_at','visibility','resource_id','narrative'],key:r=>r.event_id},
 mec6_assessments:{required:['assessment_id','participant_id','criterion_id','criterion_name','status'],optional:['protocol_id','value','evidence_class','evidence_source','assessed_at','reason_for_exit'],key:r=>`${r.assessment_id}::${r.criterion_id}`},
 model_certificates:{required:['certificate_id','name','verdict'],optional:['target_class','theorem','assumptions','parameter_provenance','proof_identity','model_risk_note'],key:r=>r.certificate_id}
};
const ALIASES={
 protocol_id:['protocol_id','study_id','study','protocol','protocol_number','study_number'],sponsor_id:['sponsor_id','sponsor','sponsor_code'],version:['version','protocol_version','amendment_version'],title:['title','study_title','protocol_title'],effective_from:['effective_from','effective_date','start_date'],effective_to:['effective_to','end_date'],stage:['stage','study_stage'],risk_class:['risk_class','risk'],requirements:['requirements','required_procedures'],
 participant_id:['participant_id','subject_id','patient_id','usubjid','subject'],state:['state','subject_status','participant_status','status'],next_visit:['next_visit','next_visit_at'],visit_id:['visit_id','visit','visit_name','event_name'],protocol_version:['protocol_version','version'],scheduled_at:['scheduled_at','visit_date','scheduled_date','start_at'],room_id:['room_id','room'],
 delegation_id:['delegation_id','delegation'],role_id:['role_id','role'],action:['action','procedure','task'],valid_from:['valid_from','start_date'],valid_to:['valid_to','expiry_date','end_date'],
 resource_id:['resource_id','resource'],type:['type','resource_type'],capacity:['capacity'],booking_id:['booking_id','booking'],start_at:['start_at','start','scheduled_at'],end_at:['end_at','end'],
 event_id:['event_id','event'],event_type:['event_type','type'],occurred_at:['occurred_at','event_time','event_date'],due_at:['due_at','deadline'],source_identity:['source_identity','source_id','source'],visibility:['visibility','roles','recipients'],narrative:['narrative','description','note'],
 assessment_id:['assessment_id','assessment'],criterion_id:['criterion_id','criterion_number'],criterion_name:['criterion_name','criterion'],value:['value','result'],evidence_class:['evidence_class','evidence_type'],evidence_source:['evidence_source','source'],assessed_at:['assessed_at','assessment_date'],reason_for_exit:['reason_for_exit','discontinuation_reason'],
 certificate_id:['certificate_id','proof_id','id'],name:['name','model_name'],verdict:['verdict','status'],target_class:['target_class','certified_class'],theorem:['theorem'],assumptions:['assumptions'],parameter_provenance:['parameter_provenance','provenance'],proof_identity:['proof_identity'],model_risk_note:['model_risk_note','risk_note']
};
const state={data:emptyData(),manifest:[],pending:[],conflicts:[],receipts:[],proof:[]};
function emptyData(){return Object.fromEntries(TYPES.map(t=>[t,[]]))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function stable(v){if(Array.isArray(v))return `[${v.map(stable).join(',')}]`;if(v&&typeof v==='object')return `{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')}}`;return JSON.stringify(v)}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function statusTag(s){const k=String(s||'info').toLowerCase();return `<span class="state ${esc(k)}">${esc(s||'info')}</span>`}
function receipt(kind,subject,payload={}){state.receipts.push({schema:'clinical-site-fabric/receipt@1',at:new Date().toISOString(),kind,subject,payload});renderLedger()}
function normalHeader(h){return String(h||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
function parseList(v){if(Array.isArray(v))return v;const s=String(v??'').trim();return s?s.split(/[|;,]/).map(x=>x.trim()).filter(Boolean):[]}
function parseMaybeJSON(v){if(v&&typeof v==='object')return v;const s=String(v??'').trim();if(!s)return null;try{return JSON.parse(s)}catch{return s}}
function bool(v){return ['1','true','yes','y'].includes(String(v).toLowerCase())}
async function sha256(buffer){const hash=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')q=false;else field+=c}else if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}if(field.length||row.length){row.push(field);rows.push(row)}if(!rows.length)return [];const headers=rows.shift().map(x=>x.trim());return rows.filter(r=>r.some(x=>String(x).trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
function parseMarkdownCertificate(text,name,hash){const field=(re,def='')=>{const m=text.match(re);return m?m[1].trim():def};const verdict=field(/\*\*Verdict:\*\*\s*`?([^`\n]+)`?/i,'UNKNOWN');const target=field(/\*\*Target certified class:\*\*\s*([^\n]+)/i,'unspecified');const risk=(text.split(/## Model-risk note/i)[1]||'').trim();const theorem=(text.split(/## Theorem[^\n]*\n/i)[1]||'').split(/\n## /)[0].trim();const prov=(text.split(/## Parameter provenance/i)[1]||'').split(/\n## /)[0].trim();const identity=(text.split(/## Proof identity/i)[1]||'').split(/\n## /)[0].trim();return {certificate_id:`CERT-${hash.slice(0,12)}`,name:name.replace(/\.(md|txt)$/i,''),verdict,target_class:target,theorem,assumptions:parseList((text.split(/## Assumptions/i)[1]||'').split(/\n## /)[0].replace(/^\s*-\s*/gm,'')),parameter_provenance:prov,proof_identity:identity,model_risk_note:risk,source_name:name,source_hash:hash}}
function inferType(name,rows){const n=name.toLowerCase();const headers=rows[0]?Object.keys(rows[0]).map(normalHeader):[];const filenameHints=[['mec6_assessments',/(mec|glp|exit)/],['model_certificates',/(certificate|exposure|pk|proof)/],['source_events',/(event|sae|safety|deviation)/],['delegations',/(delegat|dof)/],['bookings',/(booking|schedule|resource_use)/],['resources',/(resource|inventory|kit)/],['visits',/(visit|encounter)/],['participants',/(participant|subject|patient)/],['protocols',/(protocol|study)/]];for(const [t,re] of filenameHints)if(re.test(n))return t;let best=null,bestScore=0;for(const t of TYPES.filter(x=>x!=='model_certificates')){const req=CONTRACTS[t].required;let score=0;for(const f of req){const aliases=(ALIASES[f]||[f]).map(normalHeader);if(headers.some(h=>aliases.includes(h)))score++}const ratio=score/req.length;if(ratio>bestScore){best=t;bestScore=ratio}}return bestScore>=.6?best:null}
function autoMapping(type,headers){const norm=Object.fromEntries(headers.map(h=>[normalHeader(h),h]));const map={};for(const field of [...CONTRACTS[type].required,...CONTRACTS[type].optional]){for(const alias of (ALIASES[field]||[field]).map(normalHeader)){if(norm[alias]){map[field]=norm[alias];break}}}return map}
function normalize(type,row,mapping,rowIndex,fileMeta){const out={};for(const field of [...CONTRACTS[type].required,...CONTRACTS[type].optional]){const source=mapping[field];if(source!==undefined){let v=row[source];if(['requirements','visibility','assumptions'].includes(field))v=parseList(v);else if(['parameter_provenance','proof_identity'].includes(field))v=parseMaybeJSON(v);else v=String(v??'').trim();out[field]=v}}
 if(type==='model_certificates'){out.certificate_id=out.certificate_id||`CERT-${fileMeta.sha256.slice(0,12)}-${rowIndex+1}`;out.name=out.name||fileMeta.name;out.verdict=out.verdict||'UNKNOWN'}
 out._source={file_id:fileMeta.file_id,file_name:fileMeta.name,file_sha256:fileMeta.sha256,row:rowIndex+2};return out}
function merge(type,records,fileMeta){let accepted=0,rejected=0;const existing=state.data[type];for(const [i,r] of records.entries()){const missing=CONTRACTS[type].required.filter(f=>String(r[f]??'').trim()==='');if(missing.length){state.conflicts.push({kind:'missing-required',type,key:`${fileMeta.name}:${i+2}`,detail:`Missing ${missing.join(', ')}`,source:fileMeta.file_id});rejected++;continue}const key=CONTRACTS[type].key(r);const prior=existing.find(x=>CONTRACTS[type].key(x)===key);if(prior){const a={...prior};delete a._source;const b={...r};delete b._source;if(stable(a)!==stable(b)){state.conflicts.push({kind:'duplicate-conflict',type,key,detail:'Same object key carries different content; second record held.',source:fileMeta.file_id});rejected++}continue}existing.push(r);accepted++}fileMeta.imported_rows=(fileMeta.imported_rows||0)+accepted;fileMeta.rejected_rows=(fileMeta.rejected_rows||0)+rejected;fileMeta.object_type=type;fileMeta.parse_status=rejected?'warning':'parsed';receipt('records-imported',fileMeta.file_id,{type,accepted,rejected});return {accepted,rejected}}
async function handleFiles(files){for(const file of files){const buffer=await file.arrayBuffer();const hash=await sha256(buffer);const meta={file_id:`FILE-${hash.slice(0,16)}`,name:file.name,size:file.size,media_type:file.type||'application/octet-stream',sha256:hash,parse_status:'unparsed',object_type:null,imported_rows:0,rejected_rows:0};if(state.manifest.some(x=>x.sha256===hash)){meta.parse_status='warning';meta.warning='Duplicate bytes already ingested';state.manifest.push(meta);continue}state.manifest.push(meta);const ext=file.name.toLowerCase().split('.').pop();try{const text=new TextDecoder().decode(buffer);if(['csv','tsv'].includes(ext)){const rows=parseCSV(ext==='tsv'?text.replace(/\t/g,','):text);queueOrImport(meta,rows)}else if(['json','ndjson','jsonl'].includes(ext)){let value;try{value=JSON.parse(text)}catch{value=text.split(/\r?\n/).filter(Boolean).map(line=>JSON.parse(line))}await importJSONValue(meta,value)}else if(['md','markdown','txt'].includes(ext)&&/(certificate|exposure|pk|proof|report)/i.test(file.name)){const cert=parseMarkdownCertificate(text,file.name,hash);merge('model_certificates',[cert],meta)}else{meta.parse_status='unparsed';meta.warning='Source sealed by hash only; export CSV/JSON for structured ingestion.';receipt('source-sealed',meta.file_id,{name:meta.name,size:meta.size,sha256:meta.sha256})}}catch(err){meta.parse_status='error';meta.warning=String(err.message||err);receipt('parse-error',meta.file_id,{error:meta.warning})}}
 renderAll();toast(`${files.length} file${files.length===1?'':'s'} processed`)}
async function importJSONValue(meta,value){if(value&&value.schema==='clinical-site-fabric/portable-packet@2'){for(const type of TYPES){const records=value.objects?.[type]||[];if(records.length){const mapping=Object.fromEntries([...CONTRACTS[type].required,...CONTRACTS[type].optional].map(x=>[x,x]));merge(type,records.map((r,i)=>normalize(type,r,mapping,i,meta)),meta)}}meta.parse_status='parsed';receipt('portable-packet-reimported',meta.file_id,{schema:value.schema});return}
 if(value&&typeof value==='object'&&!Array.isArray(value)&&TYPES.some(t=>Array.isArray(value[t]))){for(const type of TYPES){if(Array.isArray(value[type])&&value[type].length)queueOrImport(meta,value[type],type)}return}
 if(value&&typeof value==='object'&&!Array.isArray(value)&&('parameters'in value)&&('provenance'in value)){const cert={certificate_id:`MODEL-SPEC-${meta.sha256.slice(0,12)}`,name:value.name||meta.name,verdict:'UNVERIFIED_MODEL_SPEC',target_class:`${value.compartments||'?'} compartment · ${value.elimination||'?'} · ${value.input||'?'}`,theorem:'No proof certificate supplied.',assumptions:value,parameter_provenance:value.provenance,proof_identity:null,model_risk_note:'Model specification only. No kernel attestation or clinical conclusion.',source_name:meta.name,source_hash:meta.sha256};merge('model_certificates',[cert],meta);return}
 const rows=Array.isArray(value)?value:[value];queueOrImport(meta,rows)}
function queueOrImport(meta,rows,forcedType=null){if(!rows.length){meta.parse_status='warning';meta.warning='No records found';return}const type=forcedType||inferType(meta.name,rows);const headers=Object.keys(rows[0]);if(type){const mapping=autoMapping(type,headers);const normalized=rows.map((r,i)=>normalize(type,r,mapping,i,meta));const missingCoverage=CONTRACTS[type].required.filter(f=>!mapping[f]);if(missingCoverage.length){state.pending.push({id:`PEND-${meta.file_id}-${state.pending.length}`,meta,rows,headers,type,mapping});meta.parse_status='pending';meta.warning=`Map required fields: ${missingCoverage.join(', ')}`}else merge(type,normalized,meta)}else{state.pending.push({id:`PEND-${meta.file_id}-${state.pending.length}`,meta,rows,headers,type:'protocols',mapping:{}});meta.parse_status='pending';meta.warning='Object type and field mapping required'}}
function loadSample(){clearSession(false);const metaBase={size:0,media_type:'text/csv',parse_status:'parsed',rejected_rows:0};for(const type of TYPES){const rows=structuredClone(SAMPLE[type]||[]);if(!rows.length)continue;const hash=`synthetic-${type}`;const meta={...metaBase,file_id:`SAMPLE-${type.toUpperCase()}`,name:type==='model_certificates'?'synthetic_exposure_certificate.report.md':`${type}.csv`,sha256:hash,object_type:type,imported_rows:0};state.manifest.push(meta);const mapping=Object.fromEntries([...CONTRACTS[type].required,...CONTRACTS[type].optional].map(x=>[x,x]));merge(type,rows.map((r,i)=>normalize(type,r,mapping,i,meta)),meta)}receipt('sample-pack-loaded','SYN-SITE-001',{objects:Object.fromEntries(TYPES.map(t=>[t,state.data[t].length]))});renderAll();toast('Complete synthetic pack loaded')}
function clearSession(render=true){state.data=emptyData();state.manifest=[];state.pending=[];state.conflicts=[];state.receipts=[];state.proof=[];if(render)renderAll()}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('.nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===id)));location.hash=id}
$$('.nav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
