function renderSchemas(){const e=$('#schemaList');e.innerHTML=TYPES.map(t=>`<div class="card"><strong>${esc(t)}</strong><p class="small">Required</p><code>${esc(CONTRACTS[t].required.join(', '))}</code><p class="small">Optional</p><code>${esc(CONTRACTS[t].optional.join(', '))}</code></div>`).join('')}
function renderSampleLinks(){const names=['protocols.csv','participants.csv','visits.csv','delegations.csv','resources.csv','bookings.csv','source_events.csv','mec6_assessments.csv','synthetic_exposure_certificate.report.md'];$('#sampleLinks').innerHTML=names.map((n,i)=>`<article><div class="num">${i+1}</div><div><strong>${esc(n)}</strong><div class="small">Public synthetic source</div></div><a class="button" href="samples/${encodeURIComponent(n)}" download>Download</a></article>`).join('')}
function renderManifest(){if(!state.manifest.length){$('#manifestTable').innerHTML='<div class="empty">No files in this session.</div>';return}$('#manifestTable').innerHTML=`<table><thead><tr><th>File</th><th>Type</th><th>Status</th><th>Rows</th><th>SHA-256</th><th>Note</th></tr></thead><tbody>${state.manifest.map(m=>`<tr><td><strong>${esc(m.name)}</strong><div class="small">${m.size.toLocaleString()} bytes · ${esc(m.media_type)}</div></td><td>${esc(m.object_type||'source only')}</td><td>${statusTag(m.parse_status)}</td><td>${m.imported_rows||0}${m.rejected_rows?` / ${m.rejected_rows} held`:''}</td><td class="mono">${esc(m.sha256)}</td><td>${esc(m.warning||'')}</td></tr>`).join('')}</tbody></table>`}
function renderPending(){const area=$('#pendingArea');if(!state.pending.length){area.innerHTML='';return}area.innerHTML=`<h2>Files requiring mapping</h2>`+state.pending.map(p=>{const fields=[...CONTRACTS[p.type].required,...CONTRACTS[p.type].optional];return `<div class="mapper" data-pending="${esc(p.id)}"><div class="toolbar"><strong>${esc(p.meta.name)}</strong><label>Object type<select data-role="type">${TYPES.map(t=>`<option value="${t}" ${t===p.type?'selected':''}>${t}</option>`).join('')}</select></label><span class="small">${p.rows.length} rows · headers: ${esc(p.headers.join(', '))}</span></div><div class="map-grid">${fields.map(f=>`<label>${esc(f)}${CONTRACTS[p.type].required.includes(f)?' *':''}<select data-field="${esc(f)}"><option value="">— unmapped —</option>${p.headers.map(h=>`<option value="${esc(h)}" ${p.mapping[f]===h?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`).join('')}</div><div class="toolbar"><button class="action primary" data-role="apply">Apply mapping</button><button class="action" data-role="discard">Keep hash only</button></div></div>`}).join('');
 area.querySelectorAll('[data-role="type"]').forEach(sel=>sel.addEventListener('change',e=>{const box=e.target.closest('[data-pending]');const p=state.pending.find(x=>x.id===box.dataset.pending);p.type=e.target.value;p.mapping=autoMapping(p.type,p.headers);renderPending()}));
 area.querySelectorAll('[data-role="apply"]').forEach(btn=>btn.addEventListener('click',e=>{const box=e.target.closest('[data-pending]');const p=state.pending.find(x=>x.id===box.dataset.pending);const mapping={};box.querySelectorAll('[data-field]').forEach(s=>{if(s.value)mapping[s.dataset.field]=s.value});const missing=CONTRACTS[p.type].required.filter(f=>!mapping[f]);if(missing.length){toast(`Map required fields: ${missing.join(', ')}`);return}const records=p.rows.map((r,i)=>normalize(p.type,r,mapping,i,p.meta));merge(p.type,records,p.meta);state.pending=state.pending.filter(x=>x!==p);renderAll()}));
 area.querySelectorAll('[data-role="discard"]').forEach(btn=>btn.addEventListener('click',e=>{const p=state.pending.find(x=>x.id===e.target.closest('[data-pending]').dataset.pending);p.meta.parse_status='unparsed';p.meta.warning='Kept as hash-only source by operator';state.pending=state.pending.filter(x=>x!==p);receipt('mapping-declined',p.meta.file_id,{});renderAll()}))}
function protocolMap(){const m=new Map();for(const p of state.data.protocols){if(!m.has(p.protocol_id))m.set(p.protocol_id,{sponsor_id:p.sponsor_id,versions:[]});m.get(p.protocol_id).versions.push(p)}return m}
function overlaps(a,b){return new Date(a.start_at)<new Date(b.end_at)&&new Date(b.start_at)<new Date(a.end_at)}
function collisions(){const out=[];const rmap=new Map(state.data.resources.map(r=>[r.resource_id,Number(r.capacity||1)]));for(let i=0;i<state.data.bookings.length;i++)for(let j=i+1;j<state.data.bookings.length;j++){const a=state.data.bookings[i],b=state.data.bookings[j];if(a.resource_id===b.resource_id&&overlaps(a,b)){out.push({resource_id:a.resource_id,booking_a:a.booking_id,booking_b:b.booking_id,protocol_a:a.protocol_id,protocol_b:b.protocol_id,capacity:rmap.get(a.resource_id)||1})}}return out}
function currentVersion(protocolId,at){const versions=state.data.protocols.filter(p=>p.protocol_id===protocolId).filter(p=>!p.effective_from||new Date(p.effective_from)<=new Date(at)).filter(p=>!p.effective_to||new Date(p.effective_to)>=new Date(at)).sort((a,b)=>new Date(b.effective_from)-new Date(a.effective_from));return versions[0]||null}
function integrityFindings(){const out=[...state.conflicts];const pmap=protocolMap();const participants=new Map(state.data.participants.map(x=>[x.participant_id,x]));const resources=new Set(state.data.resources.map(x=>x.resource_id));for(const p of state.data.participants){if(!pmap.has(p.protocol_id))out.push({kind:'orphan-participant',type:'participants',key:p.participant_id,detail:`Protocol ${p.protocol_id} is absent`,source:p._source?.file_id})}
 for(const v of state.data.visits){if(!participants.has(v.participant_id))out.push({kind:'orphan-visit',type:'visits',key:v.visit_id,detail:`Participant ${v.participant_id} is absent`,source:v._source?.file_id});const version=currentVersion(v.protocol_id,v.scheduled_at);if(!version)out.push({kind:'no-governing-version',type:'visits',key:v.visit_id,detail:`No protocol version governs ${v.scheduled_at}`,source:v._source?.file_id});else if(v.protocol_version!==version.version)out.push({kind:'version-mismatch',type:'visits',key:v.visit_id,detail:`Bound ${v.protocol_version}; governing version is ${version.version}`,source:v._source?.file_id})}
 for(const b of state.data.bookings)if(!resources.has(b.resource_id))out.push({kind:'orphan-booking',type:'bookings',key:b.booking_id,detail:`Resource ${b.resource_id} is absent`,source:b._source?.file_id});
 for(const e of state.data.source_events){if(e.protocol_id&&!pmap.has(e.protocol_id))out.push({kind:'orphan-event-protocol',type:'source_events',key:e.event_id,detail:`Protocol ${e.protocol_id} is absent`,source:e._source?.file_id});if(e.participant_id&&!participants.has(e.participant_id))out.push({kind:'orphan-event-participant',type:'source_events',key:e.event_id,detail:`Participant ${e.participant_id} is absent`,source:e._source?.file_id})}
 return out}
function siteQueue(){const q=[];for(const e of state.data.source_events){if(e.due_at||/missing|collision|safety|sae|positive|deviation/i.test(e.event_type)){q.push({id:e.event_id,title:e.event_type,detail:[e.protocol_id,e.participant_id,e.due_at?`due ${e.due_at}`:''].filter(Boolean).join(' · '),status:/safety|sae|positive/i.test(e.event_type)?'hold':/missing|collision/i.test(e.event_type)?'warning':'info'})}}for(const c of collisions())q.push({id:`COL-${c.booking_a}-${c.booking_b}`,title:'resource collision',detail:`${c.resource_id}: ${c.protocol_a} overlaps ${c.protocol_b}`,status:'warning'});return q}
function renderMetrics(){const finds=integrityFindings(),cols=collisions(),safety=state.data.source_events.filter(e=>/safety|sae/i.test(e.event_type));const values=[[state.data.protocols.length,'protocol versions'],[state.data.participants.length,'participants'],[state.data.source_events.length,'source events'],[cols.length,'resource collisions'],[finds.length,'integrity findings']];$('#metrics').innerHTML=values.map(([n,l])=>`<div class="metric"><b>${n}</b><span>${esc(l)}</span></div>`).join('')}
function renderSite(){renderMetrics();const q=siteQueue();$('#siteQueue').innerHTML=q.length?q.map((x,i)=>`<article><div class="num">${i+1}</div><div><strong>${esc(x.title)}</strong><div class="small">${esc(x.detail)}</div></div>${statusTag(x.status)}</article>`).join(''):'<div class="empty">No actionable objects loaded.</div>';const cols=collisions();$('#collisionTable').innerHTML=cols.length?`<table><thead><tr><th>Resource</th><th>Booking A</th><th>Booking B</th><th>Protocols</th></tr></thead><tbody>${cols.map(c=>`<tr><td>${esc(c.resource_id)}</td><td>${esc(c.booking_a)}</td><td>${esc(c.booking_b)}</td><td>${esc(c.protocol_a)} / ${esc(c.protocol_b)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No overlapping resource bookings.</div>';const ev=state.data.source_events;$('#eventTable').innerHTML=ev.length?`<table><thead><tr><th>Event</th><th>Protocol / participant</th><th>Clock</th><th>Source</th></tr></thead><tbody>${ev.map(e=>`<tr><td><strong>${esc(e.event_type)}</strong><div class="small">${esc(e.event_id)}</div></td><td>${esc(e.protocol_id||'site')}<br>${esc(e.participant_id||'')}</td><td>${esc(e.due_at||e.occurred_at||'')}</td><td><span class="source-chip">${esc(e.source_identity)}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No source events loaded.</div>'}
function renderProtocols(){const groups=[...protocolMap().entries()];$('#protocolGrid').innerHTML=groups.length?groups.map(([id,g])=>`<article class="card protocol ${esc((g.versions[0]?.risk_class||'').toLowerCase())}"><div class="eyebrow">${esc(g.sponsor_id)}</div><h2>${esc(id)}</h2><p>${esc(g.versions[0]?.title||'')}</p>${g.versions.sort((a,b)=>new Date(a.effective_from)-new Date(b.effective_from)).map(v=>`<div><strong>v${esc(v.version)}</strong> ${statusTag(v.effective_to?'completed':'active')}<div class="small">${esc(v.effective_from||'')} → ${esc(v.effective_to||'open')}</div><div>${parseList(v.requirements).map(x=>`<span class="source-chip">${esc(x)}</span>`).join('')}</div></div>`).join('<hr>')}</article>`).join(''):'<div class="empty">Import protocol versions.</div>';const rows=state.data.visits;$('#visitTable').innerHTML=rows.length?`<table><thead><tr><th>Visit</th><th>Participant</th><th>Protocol</th><th>Bound version</th><th>Scheduled</th><th>Status</th></tr></thead><tbody>${rows.map(v=>`<tr><td>${esc(v.visit_id)}</td><td>${esc(v.participant_id)}</td><td>${esc(v.protocol_id)}</td><td>${esc(v.protocol_version)}</td><td>${esc(v.scheduled_at)}</td><td>${statusTag(v.status||'info')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Import visits.</div>';const finds=integrityFindings().filter(x=>/version|protocol|visit/.test(x.kind));$('#lineageFindings').innerHTML=finds.length?finds.map(f=>`<div class="notice bad"><strong>${esc(f.kind)}:</strong> ${esc(f.key)} · ${esc(f.detail)}</div>`).join(''):'<div class="notice good"><strong>PASS.</strong> Every imported visit resolves to a governing protocol version.</div>'}
function renderAuthority(){const protocols=[...new Set(state.data.protocols.map(x=>x.protocol_id))];$('#gateProtocol').innerHTML=protocols.map(x=>`<option>${esc(x)}</option>`).join('');const d=state.data.delegations;$('#delegationTable').innerHTML=d.length?`<table><thead><tr><th>Role</th><th>Protocol</th><th>Action</th><th>Valid</th><th>Status</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.role_id)}</td><td>${esc(x.protocol_id)}</td><td>${esc(x.action)}</td><td>${esc(x.valid_from||'')} → ${esc(x.valid_to||'open')}</td><td>${statusTag(x.status||'info')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Import delegation records.</div>'}
function evaluateGate(){const role=$('#gateRole').value,protocol=$('#gateProtocol').value,action=$('#gateAction').value;const at=new Date($('#gateTime').value);const candidates=state.data.delegations.filter(d=>d.role_id===role&&d.protocol_id===protocol&&d.action===action);const active=candidates.find(d=>(!d.valid_from||new Date(d.valid_from)<=at)&&(!d.valid_to||new Date(d.valid_to)>=at)&&String(d.status).toLowerCase()!=='revoked');let outcome,detail;if(active){outcome='PASS_INTERNAL_PREPARATION';detail=`${role} has an active ${action} delegation under ${active.delegation_id}. This authorizes only the bounded internal action represented by the imported record.`}else if(candidates.length){outcome='REFUSED_STALE_OR_INACTIVE_AUTHORITY';detail=`A matching delegation exists, but none is active at ${at.toISOString()}. A downstream row cannot revive it.`}else{outcome='REFUSED_NO_AUTHORITY_RECORD';detail='No matching delegation record exists. The tool will not infer authority from job title or workflow familiarity.'}const e=$('#gateResult');e.hidden=false;e.className=`notice ${outcome.startsWith('PASS')?'good':'bad'}`;e.innerHTML=`<strong>${esc(outcome)}</strong><p>${esc(detail)}</p>`;receipt('authority-gate',`${role}:${protocol}:${action}`,{at:at.toISOString(),outcome})}
function projection(seat){const pmap=protocolMap();const sponsorFor=pid=>pmap.get(pid)?.sponsor_id||'';if(seat==='SITE')return {title:'Site operations',participants:state.data.participants.map(p=>({participant_id:p.participant_id,protocol_id:p.protocol_id,state:p.state,next_visit:p.next_visit})),events:state.data.source_events.filter(e=>parseList(e.visibility).some(r=>['PI','CRC'].includes(r))||!e.protocol_id).map(e=>({event_id:e.event_id,event_type:e.event_type,protocol_id:e.protocol_id,participant_id:e.participant_id,due_at:e.due_at,resource_id:e.resource_id,source_identity:e.source_identity})),note:'Shared operational constraints are visible. Sponsor-protected narratives and foreign sponsor source bytes are not projected.'};if(seat==='AUDITOR')return {title:'Independent auditor',participants:state.data.participants.map(p=>({participant_id:p.participant_id,protocol_id:p.protocol_id,sponsor_id:p.sponsor_id,state:p.state})),events:state.data.source_events.map(e=>({event_id:e.event_id,event_type:e.event_type,protocol_id:e.protocol_id,protocol_version:e.protocol_version,source_identity:e.source_identity,visibility:parseList(e.visibility)})),note:'Auditor receives lineage and controls, not clinical authority.'};const role=seat==='SP-A'?'MON-A':'MON-B';return {title:`${seat} monitor`,participants:state.data.participants.filter(p=>p.sponsor_id===seat).map(p=>({participant_id:p.participant_id,protocol_id:p.protocol_id,state:p.state,next_visit:p.next_visit})),events:state.data.source_events.filter(e=>sponsorFor(e.protocol_id)===seat&&parseList(e.visibility).includes(role)).map(e=>({event_id:e.event_id,event_type:e.event_type,protocol_id:e.protocol_id,participant_id:e.participant_id,due_at:e.due_at,source_identity:e.source_identity})),note:`Projection contains only ${seat} objects admitted to ${role}.`}}
function renderProjection(){const seat=$('#projectionSeat').value,p=projection(seat);$('#projectionResult').innerHTML=`<div class="notice info"><strong>${esc(p.title)}</strong> · ${esc(p.note)}</div><div class="two"><div><h2>Participants</h2><div class="table-wrap"><table><tbody>${p.participants.length?p.participants.map(x=>`<tr><td><code>${esc(x.participant_id)}</code></td><td>${esc(x.protocol_id)}</td><td>${esc(x.state)}</td></tr>`).join(''):'<tr><td>No participants</td></tr>'}</tbody></table></div></div><div><h2>Events</h2><div class="table-wrap"><table><tbody>${p.events.length?p.events.map(x=>`<tr><td><code>${esc(x.event_id)}</code></td><td>${esc(x.event_type)}</td><td>${esc(x.protocol_id||'site')}</td></tr>`).join(''):'<tr><td>No events</td></tr>'}</tbody></table></div></div></div>`}
function leakageChallenge(){const a=JSON.stringify(projection('SP-A')),b=JSON.stringify(projection('SP-B'));const pass=!a.includes('SP-B')&&!a.includes('B301-')&&!b.includes('SP-A')&&!b.includes('A101-')&&!b.includes('A202-');const e=$('#leakResult');e.hidden=false;e.className=`notice ${pass?'good':'bad'}`;e.innerHTML=`<strong>${pass?'PASS':'FAIL'}.</strong> ${pass?'Foreign sponsor identifiers are absent from both serialized projections.':'At least one foreign sponsor identifier entered a projection.'}`;receipt('leakage-challenge','sponsor-projections',{pass})}
function mecGroups(){const m=new Map();for(const x of state.data.mec6_assessments){if(!m.has(x.participant_id))m.set(x.participant_id,[]);m.get(x.participant_id).push(x)}return m}
function certificateAssessment(c){const risk=String(c.model_risk_note||'').trim(),prov=c.parameter_provenance,identity=c.proof_identity;const complete=Boolean(risk&&prov&&identity&&String(c.verdict).toUpperCase()==='CERTIFIED');return {complete,status:complete?'model-relative-certified':'refused-scope-incomplete',may_set_clinical_disposition:false,detail:complete?'The certificate has theorem scope, provenance, proof identity, and a model-risk note. It remains attached to the model only.':'The artifact lacks one or more required scope controls and is refused as a certificate.'}}
function renderMec(){const groups=mecGroups(),ids=[...groups.keys()];$('#mecParticipant').innerHTML=ids.map(x=>`<option>${esc(x)}</option>`).join('');const id=$('#mecParticipant').value||ids[0];const rows=groups.get(id)||[];if(!rows.length){$('#mecCard').innerHTML='<div class="empty">Import MEC-6 assessment rows.</div>'}else{const reason=rows.find(x=>x.reason_for_exit)?.reason_for_exit||'not supplied';const hasHold=rows.some(x=>['hold','fail','incomplete'].includes(String(x.status).toLowerCase()));$('#mecCard').innerHTML=`<div class="notice bad"><strong>System result:</strong> ${hasHold?'HOLD_CLINICAL_DISPOSITION_PREPARE_HARM_REDUCTION':'REVIEW_REQUIRED_NO_AUTOMATIC_CLEARANCE'}</div><p><strong>Exit pressure:</strong> ${esc(reason)}</p>${rows.sort((a,b)=>Number(a.criterion_id)-Number(b.criterion_id)).map(x=>`<div class="criterion"><strong>${esc(x.criterion_name)}</strong>${statusTag(x.status)}<div>${esc(x.value||'')}<div class="small">${esc(x.evidence_class||'')} · ${esc(x.evidence_source||'')}</div></div></div>`).join('')}<div class="notice"><strong>Prohibited output:</strong> <code>safe_to_stop</code>. A treating clinician retains disposition authority.</div>`}
 const checks=[['GSK-01','Executable artifact required','A marketing description or model specification without a certificate remains unverified.'],['GSK-02','Theorem scope and assumptions','A green build proves only the declared model under its declared assumptions.'],['GSK-03','Parameter provenance','Every interval and fit must retain dataset, method, and origin.'],['GSK-04','Model-risk note','Off-model physiology, heterogeneity, adherence, and interval error remain outside the proof.'],['GLP1-01','On-drug stability is not off-drug durability','Weight stability cannot be promoted into successful discontinuation.'],['GLP1-02','External stopping pressure stays separate','Coverage, cost, supply, or side effects do not create clinical readiness.'],['GLP1-03','Missing evidence does not default green','Incomplete, self-reported, conflicting, and measured evidence retain their class.']];$('#gskChecks').innerHTML=checks.map((x,i)=>`<article><div class="num">${i+1}</div><div><strong>${esc(x[1])}</strong><div class="small">${esc(x[2])}</div></div>${statusTag('active')}</article>`).join('');const certs=state.data.model_certificates;$('#certificateList').innerHTML=certs.length?certs.map(c=>{const a=certificateAssessment(c);return `<div class="card"><div class="eyebrow">${esc(c.certificate_id)}</div><h3>${esc(c.name)}</h3>${statusTag(a.status)}<p>${esc(a.detail)}</p><p class="small">Verdict: ${esc(c.verdict)} · target: ${esc(c.target_class||'')}</p><div class="notice"><strong>Clinical authority:</strong> none. May set disposition: ${String(a.may_set_clinical_disposition)}</div></div>`}).join(''):'<div class="empty">Drop an AXM Exposure-style Markdown report or JSON model spec.</div>'}
function renderIntegrity(){const finds=integrityFindings();$('#integrityTable').innerHTML=finds.length?`<table><thead><tr><th>Kind</th><th>Object</th><th>Detail</th><th>Source</th></tr></thead><tbody>${finds.map(f=>`<tr><td>${statusTag(f.kind.includes('conflict')||f.kind.includes('orphan')||f.kind.includes('mismatch')?'warning':'info')}</td><td>${esc(f.type)} · ${esc(f.key)}</td><td>${esc(f.detail)}</td><td>${esc(f.source||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="notice good"><strong>PASS.</strong> No duplicate, orphan, or protocol-version findings.</div>'}
function renderLedger(){const rows=[...state.receipts].reverse();$('#ledger').innerHTML=rows.length?rows.map(r=>`<article><strong>${esc(r.kind)}</strong> · ${esc(r.subject)}<br>${esc(r.at)}<br>${esc(JSON.stringify(r.payload))}</article>`).join(''):'<article>No session receipts.</article>'}
function portablePacket(){return {schema:'clinical-site-fabric/portable-packet@2',version:'0.2.0',exported_at:new Date().toISOString(),evidence_tier:'de-identified or synthetic local browser normalization; not clinically validated',boundaries:{clinical_use:'prohibited',phi:'not accepted by policy',external_effects:'none',original_bytes:'not included',clinical_authority:'human only'},objects:Object.fromEntries(TYPES.map(t=>[t,state.data[t].map(x=>{const y={...x};delete y._source;return y})])),source_manifest:state.manifest.map(m=>({file_id:m.file_id,name:m.name,size:m.size,media_type:m.media_type,sha256:m.sha256,parse_status:m.parse_status,object_type:m.object_type,imported_rows:m.imported_rows,rejected_rows:m.rejected_rows||0,warning:m.warning||''})),integrity_findings:integrityFindings(),receipts:state.receipts,runtime_dependency:'none'} }
async function packetHash(){const text=stable(portablePacket());return sha256(new TextEncoder().encode(text))}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
async function exportPacket(){const p=portablePacket();p.packet_sha256=await packetHash();receipt('portable-export','clinical-site-fabric',{packet_sha256:p.packet_sha256});download('clinical-site-fabric-portable-packet.json',JSON.stringify(p,null,2)+'\n');renderDigest();toast('Portable packet exported')}
function exportNormalized(){const data={schema:'clinical-site-fabric/normalized-tables@1',objects:portablePacket().objects};download('clinical-site-fabric-normalized-tables.json',JSON.stringify(data,null,2)+'\n');receipt('normalized-export','clinical-site-fabric',{})}
async function renderDigest(){try{$('#packetDigest').textContent=`sha256:${await packetHash()}`}catch{$('#packetDigest').textContent='digest unavailable'}}
function proofCells(){const pmap=protocolMap();const pa=projection('SP-A'),pb=projection('SP-B'),cols=collisions(),finds=integrityFindings();const expired=state.data.delegations.find(d=>d.delegation_id==='DEL-CRC-SPECIMEN-002')||state.data.delegations.find(d=>String(d.status).toLowerCase()==='expired');const mec=[...mecGroups().values()].flat();const certs=state.data.model_certificates.map(certificateAssessment);const packet=portablePacket();return [
 {id:'INGEST-01',name:'Real file intake contract',pass:state.manifest.length>0&&state.manifest.every(m=>m.sha256),detail:'Every source artifact carries a browser-computed SHA-256 and parse status.'},
 {id:'SCHEMA-01',name:'Structured object reconstruction',pass:state.data.protocols.length>=3&&state.data.participants.length>=1&&state.data.source_events.length>=1,detail:'Protocol, participant, and source-event objects were reconstructed from imported records.'},
 {id:'SPONSOR-01',name:'Sponsor A isolation',pass:!JSON.stringify(pa).includes('SP-B')&&!JSON.stringify(pa).includes('B301-'),detail:'Sponsor A projection contains no Sponsor B identifiers.'},
 {id:'SPONSOR-02',name:'Sponsor B isolation',pass:!JSON.stringify(pb).includes('SP-A')&&!JSON.stringify(pb).includes('A101-')&&!JSON.stringify(pb).includes('A202-'),detail:'Sponsor B projection contains no Sponsor A identifiers.'},
 {id:'SITE-01',name:'Site-wide coordination',pass:cols.length>0,detail:'The site detects a shared resource collision across protocols without merging sponsor projections.'},
 {id:'VERSION-01',name:'Protocol-version lineage',pass:!finds.some(f=>f.kind==='version-mismatch'||f.kind==='no-governing-version'),detail:'Every visit binds to the protocol version effective when the work occurs.'},
 {id:'AUTH-01',name:'Expired authority remains expired',pass:Boolean(expired)&&String(expired.status).toLowerCase()==='expired',detail:'An expired delegation exists and is available to refuse a stale action.'},
 {id:'SAFETY-01',name:'Safety clock retained',pass:state.data.source_events.some(e=>/safety|sae/i.test(e.event_type)&&e.due_at),detail:'At least one source-created safety event retains a due clock.'},
 {id:'GLP1-01',name:'Stopping pressure is separate',pass:mec.some(x=>x.reason_for_exit)&&mec.some(x=>['hold','fail','incomplete'].includes(String(x.status).toLowerCase())),detail:'External exit pressure coexists with unresolved clinical evidence.'},
 {id:'GSK-01',name:'Model proof stays model-relative',pass:certs.length>0&&certs.every(c=>c.may_set_clinical_disposition===false),detail:'No model certificate can set patient disposition.'},
 {id:'PORT-01',name:'Provider-loss packet',pass:packet.runtime_dependency==='none'&&TYPES.every(t=>Array.isArray(packet.objects[t])),detail:'The normalized objects and source manifest export without this runtime.'},
 {id:'REPLAY-01',name:'Portable re-import schema',pass:packet.schema==='clinical-site-fabric/portable-packet@2'&&packet.source_manifest.length===state.manifest.length,detail:'The exported packet contains the complete normalized object families and file receipts.'}
]}
function runProof(){state.proof=proofCells();const passed=state.proof.filter(x=>x.pass).length;receipt('admission-run','clinical-site-fabric',{passed,total:state.proof.length,failed:state.proof.filter(x=>!x.pass).map(x=>x.id)});renderProof();toast(`${passed}/${state.proof.length} admission cells passed`)}
function renderProof(){const cells=state.proof.length?state.proof:proofCells().map(x=>({...x,pass:null}));$('#proofGrid').innerHTML=cells.map(c=>`<article class="proof"><header><div><div class="eyebrow">${esc(c.id)}</div><strong>${esc(c.name)}</strong></div>${c.pass===null?statusTag('pending'):statusTag(c.pass?'pass':'fail')}</header><p>${esc(c.detail)}</p></article>`).join('');if(state.proof.length){const p=state.proof.filter(x=>x.pass).length;const e=$('#proofSummary');e.className=`notice ${p===state.proof.length?'good':'bad'}`;e.innerHTML=`<strong>${p}/${state.proof.length} PASS.</strong> ${state.proof.filter(x=>!x.pass).map(x=>x.id).join(', ')||'All admitted cells passed.'}`}else{$('#proofSummary').className='notice info';$('#proofSummary').textContent='Admission cells not run.'}}
function renderAll(){renderSchemas();renderSampleLinks();renderManifest();renderPending();renderSite();renderProtocols();renderAuthority();renderProjection();renderMec();renderIntegrity();renderLedger();renderProof();renderDigest()}
$('#fileInput').addEventListener('change',e=>handleFiles([...e.target.files]));const dz=$('#dropZone');['dragenter','dragover'].forEach(k=>dz.addEventListener(k,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(k=>dz.addEventListener(k,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>handleFiles([...e.dataTransfer.files]));$('#loadSample').addEventListener('click',loadSample);$('#clearAll').addEventListener('click',()=>{clearSession();toast('Session cleared')});$('#clearAllTop').addEventListener('click',()=>{clearSession();toast('Session cleared')});$('#exportTop').addEventListener('click',exportPacket);$('#projectionSeat').addEventListener('change',renderProjection);$('#runLeak').addEventListener('click',leakageChallenge);$('#runGate').addEventListener('click',evaluateGate);$('#mecParticipant').addEventListener('change',renderMec);$('#runProof').addEventListener('click',runProof);$('#exportPacket').addEventListener('click',exportPacket);$('#exportNormalized').addEventListener('click',exportNormalized);$('#closeDialog').addEventListener('click',()=>$('#detailDialog').close());
renderAll();if(location.hash)showView(location.hash.slice(1));if(new URLSearchParams(location.search).get('selftest')==='1'){loadSample();state.proof=proofCells();const passed=state.proof.filter(x=>x.pass).length;document.body.dataset.selftest=passed===state.proof.length?'pass':'fail';document.body.dataset.selftestPassed=String(passed);document.body.dataset.selftestTotal=String(state.proof.length);renderProof();}
