(async()=>{
  'use strict';
  const DATA_URL='data/estate.json';
  const STORAGE='mw-operating-fabric-v0.1.0';
  const ALLOWED_VIEWS=['picture','projects','commons','pilotage','money','perimeter','architecture','handoff'];
  let data;
  let state={view:'picture',project:null,layer:null,decision:'ALL',search:'',reviewNote:''};
  const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  function escapeText(v){return String(v??'');}
  try{if(window.__MW_DATA__) data=window.__MW_DATA__; else data=await fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`estate ${r.status}`);return r.json()});}catch(err){document.body.innerHTML=`<main style="padding:2rem;font-family:sans-serif"><h1>Operating Fabric failed to load</h1><p>${escapeText(err.message)}</p></main>`;return;}
  state.project=data.modules[0]?.id||null;state.layer=data.architecture_layers[0]?.layer||null;
  try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&typeof saved==='object'){state={...state,...saved};}}catch{}
  const params=new URL(location.href).searchParams;if(ALLOWED_VIEWS.includes(params.get('view')))state.view=params.get('view');
  function save(){localStorage.setItem(STORAGE,JSON.stringify(state));const u=new URL(location.href);u.searchParams.set('view',state.view);history.replaceState(null,'',u);}
  function setView(view){if(!ALLOWED_VIEWS.includes(view))return;state.view=view;save();$$('.view').forEach(p=>p.hidden=p.dataset.panel!==view);$$('.nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.view===view?'page':'false'));$('#main').focus({preventScroll:true});if(view==='perimeter')renderPerimeter();}
  $$('.nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
  $('#theme').addEventListener('click',()=>{const current=document.documentElement.dataset.theme||'light';const next=current==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('mw-operating-theme',next)});
  $('#metric-capacity').textContent=data.capacities.length;$('#metric-modules').textContent=data.modules.length;$('#metric-perimeter').textContent=data.perimeter.length;
  function cell(t,cl=''){const d=document.createElement('div');if(cl)d.className=cl;d.textContent=t;return d}
  function renderEstate(){const box=$('#estate-table');box.replaceChildren();const head=document.createElement('div');head.className='estate-row head';['Program / organ','State','Institutional job','What Manzanita owns','Commodity / handoff'].forEach(x=>head.append(cell(x)));box.append(head);data.modules.forEach(m=>{const r=document.createElement('div');r.className='estate-row';const name=document.createElement('div');name.innerHTML=`<b>${m.name}</b><br><small>${m.class}</small>`;const st=document.createElement('div');st.innerHTML=`<span class="state">${m.state}</span>`;r.append(name,st,cell(m.job),cell(m.owns),cell(`${m.commodity} ${m.handoff}`));box.append(r)})}
  function renderControls(){const box=$('#control-grid');box.replaceChildren();data.control_questions.forEach(q=>{const a=document.createElement('article');a.innerHTML=`<p class="eyebrow">${q.id.toUpperCase()}</p><h4>${q.question}</h4><p>${q.answer}</p>`;box.append(a)})}
  function renderProjects(){const list=$('#project-list'),detail=$('#project-detail');list.replaceChildren();data.modules.forEach(m=>{const b=document.createElement('button');b.type='button';b.role='tab';b.dataset.project=m.id;b.setAttribute('aria-selected',String(state.project===m.id));b.innerHTML=`<b>${m.name}</b><br><small>${m.state}</small>`;b.addEventListener('click',()=>{state.project=m.id;save();renderProjects()});list.append(b)});const m=data.modules.find(x=>x.id===state.project)||data.modules[0];detail.innerHTML=`<p class="eyebrow">${m.class.toUpperCase()}</p><h3>${m.name}</h3><div class="meta"><span class="state">${m.state}</span></div><p>${m.job}</p><dl><div><dt>Institution owns</dt><dd>${m.owns}</dd></div><div><dt>Commodity layer</dt><dd>${m.commodity}</dd></div><div><dt>Handoff</dt><dd>${m.handoff}</dd></div></dl><a class="secondary" href="${m.route}">Open related surface</a>`}
  function renderCapacity(selector='#capacity-grid'){const box=$(selector);if(!box)return;box.replaceChildren();data.capacities.forEach(c=>{const a=document.createElement('article');a.innerHTML=`<p class="eyebrow">${c.id.toUpperCase()}</p><h4>${c.label}</h4><p>${c.question}</p><small>${c.system}</small>`;box.append(a)})}
  function renderMoney(){const box=$('#money-table');box.replaceChildren();const h=document.createElement('div');h.className='money-row head';['Lane','Purpose','Canonical record','Processor role','Standing'].forEach(x=>h.append(cell(x)));box.append(h);data.money_lanes.forEach(m=>{const r=document.createElement('div');r.className='money-row';r.append(cell(m.lane),cell(m.purpose),cell(m.canonical),cell(m.processor),cell(m.status));box.append(r)})}
  function renderPerimeter(){const decision=$('#decision-filter').value||state.decision;const search=($('#perimeter-search').value||state.search).trim().toLowerCase();state.decision=decision;state.search=search;save();const box=$('#perimeter-table');box.replaceChildren();const h=document.createElement('div');h.className='perimeter-row head';['System','Function','Decision','Capture risk','Why'].forEach(x=>h.append(cell(x)));box.append(h);data.perimeter.filter(p=>(decision==='ALL'||p.decision===decision)&&(!search||`${p.name} ${p.function} ${p.why}`.toLowerCase().includes(search))).forEach(p=>{const r=document.createElement('div');r.className='perimeter-row';r.append(cell(p.name),cell(p.function),cell(p.decision,'decision'),cell(p.capture),cell(p.why));box.append(r)});if(box.children.length===1){const empty=document.createElement('p');empty.style.padding='1rem';empty.textContent='No commodity candidates match this filter.';box.append(empty)}}
  $('#decision-filter').value=state.decision;$('#perimeter-search').value=state.search;$('#decision-filter').addEventListener('change',renderPerimeter);$('#perimeter-search').addEventListener('input',renderPerimeter);
  function renderArchitecture(){const list=$('#layer-list'),detail=$('#layer-detail');list.replaceChildren();data.architecture_layers.forEach(l=>{const b=document.createElement('button');b.type='button';b.role='tab';b.setAttribute('aria-selected',String(state.layer===l.layer));b.textContent=l.layer;b.addEventListener('click',()=>{state.layer=l.layer;save();renderArchitecture()});list.append(b)});const l=data.architecture_layers.find(x=>x.layer===state.layer)||data.architecture_layers[0];detail.innerHTML=`<p class="eyebrow">LAYER</p><h3>${l.layer}</h3><h4>Controlling question</h4><p>${l.question}</p><h4>What the institution owns</h4><p>${l.own}</p><h4>Capture failure</h4><p class="warning">${l.do_not_outsource}</p>`}
  function renderHandoff(){const ol=$('#handoff-sequence');ol.replaceChildren(...data.handoff.sequence.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));const links=$('#handoff-links');links.replaceChildren(...data.handoff.links.map(l=>{const a=document.createElement('a');a.href=l.href;a.textContent=l.label;return a}));$('#review-note').value=state.reviewNote||''}
  $('#review-note').addEventListener('input',e=>{state.reviewNote=e.target.value.slice(0,4000);save()});$('#reset-note').addEventListener('click',()=>{state.reviewNote='';$('#review-note').value='';save();$('#export-status').textContent='Local review note cleared.'});
  $('#export-packet').addEventListener('click',()=>{const packet={schema_version:'mw.operating-fabric.packet/0.1.0',exported_at:new Date().toISOString(),release:data.release,principle:data.principle,capacities:data.capacities,modules:data.modules,money_lanes:data.money_lanes,architecture_layers:data.architecture_layers,perimeter:data.perimeter,control_questions:data.control_questions,handoff:data.handoff,local_review_note:state.reviewNote||'',ui:{project:state.project,layer:state.layer}};const blob=new Blob([JSON.stringify(packet,null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Manzanita_Works_Operating_Fabric_v0.1.0_packet.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);$('#export-status').textContent='Portable operating packet exported locally. No external system was contacted.'});
  renderEstate();renderControls();renderProjects();renderCapacity();renderCapacity('#commons-capacities');renderMoney();renderPerimeter();renderArchitecture();renderHandoff();setView(state.view);
})();
