#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "case-zero"

TOOL_README = """# Case Zero · Tier Desk × RedCat external qualification

A local-only workbench for testing Tier Desk against one real, failed client engagement without asking RedCat to upload the raw engagement record or trust a hosted runtime.

Public route:

```text
https://bigbirdreturns.github.io/axm-tools/case-zero/
```

## What the page does

The page is one self-contained HTML file. It can:

- accept a folder or selected files inside the browser;
- hash every selected file locally;
- classify surviving evidence by commercial, communication, delivery, technical, economics, acceptance, change, outcome, source-code, or unknown shape;
- count credential- and PII-shaped signals without retaining or exporting matched values;
- show which of ten Case Zero analysis jobs have enough source classes to begin and which remain held;
- export a body-free local manifest or a path-pseudonymized share-safe preview; and
- download a deterministic Python runner and a compact pre-read from bytes embedded in the page.

The synthetic example exercises the browser path before any client material is selected.

## What it does not do

The page makes no network requests. It does not upload source files, call a model, contact the historical client, interpret the engagement, calculate a counterfactual, or authorize a shadow pilot.

The browser stops at the evidence and execution floor. A substantive Case Zero result still requires source-addressed reconstruction, explicit missing and contradictory evidence, actual-versus-counterfactual economics, and RedCat architect challenge.

## Authority

RedCat retains the client relationship, pricing, commercial terms, brand, scope and delivery authority, disclosure decisions, and final disposition. Tier Desk may reconstruct, decompose, verify, and report. It may not contact or represent the historical client. Models and tools produce candidate analysis only.

## Operating paths

### Browser preview

Open `index.html`, select a folder or files, and choose **Build local preview**. The exports contain manifests, holds, coverage, and the proposed analysis queue. They contain no selected source-file contents.

### Deterministic local runner

Download `downloads/redcat_case_zero_runner_v0.1.zip`, download `casezero.py` from the page, or use the readable source under `runner/`:

```powershell
python casezero.py intake `
  --input "D:\\RedCat\\CaseZero\\raw" `
  --output "D:\\RedCat\\CaseZero\\intake" `
  --case-id "REDCAT-CZ-001" `
  --custody-mode "redcat_local" `
  --as-of "2026-09-01T12:00:00Z"
```

The runner uses only the Python standard library and makes no network calls.

## Repository layout

```text
case-zero/
├── README.md
├── index.html
├── QUALIFICATION.json
├── downloads/
│   ├── CASE_ZERO_PRE_READ.pdf
│   └── redcat_case_zero_runner_v0.1.zip
├── runner/
│   ├── casezero.py
│   ├── test_casezero.py
│   ├── protocol, data, economics, and review contracts
│   └── PACKAGE_SHA256SUMS
├── scripts/
│   ├── build_release.py
│   └── integrate_root.py
└── tests/
    ├── validate.py
    └── browser_test.py
```

## File ownership

There are no machine-owned client or case files in this tool.

- `index.html`, `README.md`, `runner/`, `scripts/`, `tests/`, and the workflow are steward-owned source.
- `QUALIFICATION.json` is deterministically generated by `tests/validate.py`.
- `downloads/` contains frozen v0.1 release objects generated from the readable source. A content change requires a new version and new identities.
- Browser-selected client material is never written into the repository.

## Qualification

```bash
python case-zero/scripts/build_release.py
python case-zero/scripts/integrate_root.py
python case-zero/tests/validate.py
node --check /tmp/case-zero-inline.js
python -m unittest discover -s case-zero/runner -p 'test_casezero.py' -v
python case-zero/tests/browser_test.py
```

The browser campaign serves the real route over loopback, refuses external requests, executes the synthetic case, tests the credential hold, downloads and inspects the runner, pre-read, local manifest, and share-safe packet, and checks mobile and 200-percent-text composition.

## What can rot

- `webkitdirectory`, drag-and-drop, clipboard, and Blob-download APIs may change.
- Browser download permissions may change.
- Content Security Policy support may change.
- GitHub Pages and workflow actions will eventually require mechanical upgrades.
- The filename classifier is a first-pass projection, not a semantic parser; ambiguity must remain visible.

The durable properties are local custody, body-free preview export, exact hashes, visible holds, ten bounded analysis jobs, RedCat ownership of the client relationship, and refusal to manufacture a conclusion from incomplete evidence.

## Controlling question

Would this package have let RedCat decide earlier, quote more safely, and stop or re-scope before unpaid work accumulated?
"""

README_ROW = "| [`case-zero/`](case-zero/) | Local external-qualification workbench for testing one failed client engagement: hashes files in-browser, surfaces privacy and evidence holds, projects a ten-job analysis floor, and exports body-free or pseudonymized packets without uploading source bytes | [Case Zero workbench](https://bigbirdreturns.github.io/axm-tools/case-zero/) — local-only preview plus deterministic runner |"

INDEX_CARD = """
<div class="tool">
  <div class="title"><a href="case-zero/">Case Zero · Tier Desk × RedCat</a></div>
  <div class="desc">A local-only external qualification workbench for one real failed engagement. Drop a redacted folder to hash the surviving record, expose privacy and missing-evidence holds, inspect the ten-job analysis floor, and export a body-free or pseudonymized packet without uploading source bytes or contacting the historical client.</div>
  <a class="open" href="case-zero/">Open Case Zero →</a>
</div>
"""

CONTINUITY_LINE = "- `case-zero/` — local-only external qualification workbench for one failed engagement; browser custody, deterministic runner, body-free preview, ten-job floor, and RedCat-owned client boundary."


def integrate_readme() -> None:
    path = ROOT / "README.md"
    text = path.read_text(encoding="utf-8")
    if "[`case-zero/`](case-zero/)" not in text:
        lines = text.splitlines()
        position = next((index + 1 for index, line in enumerate(lines) if line.startswith("| [`clinical-site-fabric/`]")), None)
        if position is None:
            position = next(index + 1 for index, line in enumerate(lines) if line.startswith("|------"))
        lines.insert(position, README_ROW)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def integrate_index() -> None:
    path = ROOT / "index.html"
    text = path.read_text(encoding="utf-8")
    if 'href="case-zero/"' not in text:
        marker = '<div class="tool">\n  <div class="title"><a href="polybolos/">'
        if marker not in text:
            raise SystemExit("root index integration marker not found")
        text = text.replace(marker, INDEX_CARD + "\n" + marker, 1)
        path.write_text(text, encoding="utf-8", newline="\n")


def integrate_continuity() -> None:
    path = ROOT / "CONTINUITY.md"
    text = path.read_text(encoding="utf-8")
    if CONTINUITY_LINE not in text:
        marker = "- `pta-tracker/` — the living tool: nightly legislation fetch for a K-6"
        if marker not in text:
            raise SystemExit("continuity integration marker not found")
        text = text.replace(marker, CONTINUITY_LINE + "\n" + marker, 1)
        path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    (TOOL / "README.md").write_text(TOOL_README, encoding="utf-8", newline="\n")
    integrate_readme()
    integrate_index()
    integrate_continuity()
    print("CASE_ZERO_ROOT_INTEGRATION_PASS")


if __name__ == "__main__":
    main()
