// Regression checks for the actual report function embedded in the page.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const start=html.indexOf('function buildBoardReport(');
const end=html.indexOf('const clearReportBtn=',start);
const scope={inSchoolScope:c=>!c.schools||c.schools.includes('ha')};
vm.createContext(scope);vm.runInContext(html.slice(start,end),scope);
const p=JSON.parse(readFileSync(new URL('../data/parent.json',import.meta.url),'utf8'));
const report=scope.buildBoardReport(p,new Date(2026,8,22,12));
assert.match(report,/PTA LEGISLATION UPDATE - DRAFT/);
assert.match(report,/mobile-device policy/);
assert.match(report,/SOURCES/);
assert.doesNotMatch(report,/BOARD DISCUSSION|FOLLOW-UPS|Coverage counts|Owner:/);
assert.match(report,/school-specific phone/);
assert.match(scope.buildBoardReport(null),/unavailable/);
assert.match(scope.buildBoardReport(p,new Date(2026,8,24)),/^REVIEW REQUIRED/);
const after=scope.buildBoardReport(p,new Date(2026,8,23));
assert.match(after,/Follow-up required: September 22/);
assert.doesNotMatch(after,/Parents can speak at the board/);
const bad=structuredClone(p);bad.board_report.card_ids.push('missing-card');
assert.match(scope.buildBoardReport(bad,new Date(2026,8,22)),/^REVIEW REQUIRED/);
const foreign=structuredClone(p);foreign.in_effect[0].schools=['other'];
assert.match(scope.buildBoardReport(foreign,new Date(2026,8,22)),/^REVIEW REQUIRED/);
const noSource=structuredClone(p);delete noSource.in_effect[0].source_url;
assert.match(scope.buildBoardReport(noSource,new Date(2026,8,22)),/^REVIEW REQUIRED/);
console.log('PASS: reviewed report, missing data/source, expired review, past meeting and school scope');

// Exercise the actual generate/clear handlers, including error-state controls.
const elements=Object.fromEntries(['gen','clear-report'].map(id=>[id,{style:{},focus(){this.focused=true;}}]));
scope.document={getElementById:id=>elements[id]};
scope.report={style:{},textContent:''};scope.copyBtn={style:{},textContent:''};scope.shareBtn={style:{}};
scope.t=k=>k;scope.navigator={share(){}};scope.PARENT=p;
const actionEnd=html.indexOf('copyBtn.onclick=',end);
vm.runInContext(html.slice(end,actionEnd),scope);
// Isolate button behavior from the machine's clock; date checks ran above.
scope.buildBoardReport=()=>report;
elements.gen.onclick();
assert.equal(scope.copyBtn.style.display,'inline-block');
assert.equal(scope.shareBtn.style.display,'inline-block');
elements['clear-report'].onclick();
assert.equal(scope.report.textContent,'');
for(const el of [scope.report,scope.copyBtn,scope.shareBtn,elements['clear-report']])assert.equal(el.style.display,'none');
assert.equal(elements.gen.focused,true);
elements.gen.onclick();assert.equal(scope.report.textContent,report);
scope.buildBoardReport=()=> 'REVIEW REQUIRED: expired';elements.gen.onclick();
assert.equal(scope.copyBtn.style.display,'none');assert.equal(scope.shareBtn.style.display,'none');
assert.equal(elements['clear-report'].style.display,'inline-block');
console.log('PASS: generate, clear, regenerate and error-state controls');
