function canonicalizeColumns(columns){const normed=columns.map(normalizeHeader).filter(Boolean),reverse={};for(const [canon,names] of Object.entries(FIELD_SYNONYMS)){for(const n of normed){if(names.includes(n)&&!reverse[canon])reverse[canon]=n}}return {normed,reverse}}
function buildRecords(headers,dataRows,rowOffset=2){const normed=headers.map(normalizeHeader);return dataRows.slice(0,5000).map((r,i)=>{const o={__row:i+rowOffset};normed.forEach((h,ci)=>{if(h)o[h]=r[ci]});return o})}
function headerCandidateScore(headers,surfaceHint){const {reverse}=canonicalizeColumns(headers);let best=0;for(const [surface,rule] of Object.entries(SURFACE_RULES)){let hits=0;for(const group of rule.requiredAny)if(group.some(g=>reverse[g]))hits+=3;hits+=rule.recommended.filter(r=>reverse[r]).length;if(surfaceHint&&surfaceHint.toLowerCase().includes(surface))hits+=2;best=Math.max(best,hits)}return best+Math.min(1,headers.filter(x=>String(x??"").trim()).length/20)}
function chooseHeaderAndRows(rows,surfaceHint){if(!rows.length)return {headers:[],dataRows:[],headerIndex:0};let best={score:-1,index:0};for(let i=0;i<Math.min(25,rows.length);i++){const headers=rows[i]||[],nonempty=headers.filter(x=>String(x??"").trim()).length;if(!nonempty)continue;const score=headerCandidateScore(headers,surfaceHint)-(nonempty===1?1.5:0);if(score>best.score)best={score,index:i}}const headers=rows[best.index]||[],dataRows=rows.slice(best.index+1).filter(r=>r.some(x=>String(x??"").trim()));return {headers,dataRows,headerIndex:best.index}}
function scoreTable(columns,rowsCount,surfaceHint){
  const {normed,reverse}=canonicalizeColumns(columns),candidates=[];
  for(const [surface,rule] of Object.entries(SURFACE_RULES)){const missingMin=[];let reqHits=0;for(const group of rule.requiredAny){const hit=group.some(g=>reverse[g]);if(hit)reqHits++;else missingMin.push(group)}const missingRec=rule.recommended.filter(r=>!reverse[r]);let score=reqHits*3+rule.recommended.filter(r=>reverse[r]).length;if(surfaceHint&&surfaceHint.toLowerCase().includes(surface))score+=2;candidates.push({score,surface,hardOk:missingMin.length===0,missingMin,missingRec,rule})}
  candidates.sort((a,b)=>b.score-a.score);const best=candidates[0];let status,reason;if(rowsCount===0){status="FAIL";reason="No data rows detected."}else if(best.hardOk){status=best.missingRec.length?"PASS_WITH_GAPS":"PASS";reason=best.missingRec.length?"Minimum fields are present, but useful context is missing.":"Required and recommended fields are present."}else{status="FAIL";reason="Missing minimum fields for the best-matching surface."}
  return {status,surfaceType:best.surface,evidenceTierCandidate:best.rule.tier,passesAs:best.rule.passesAs,rowsCount,columnsDetected:normed,canonicalFieldsDetected:Object.keys(reverse).sort(),fieldMap:reverse,missingMinimumGroups:best.missingMin,missingRecommendedFields:best.missingRec,reason,limitations:limitationsFor(status,best.surface,best.missingRec)};
}
function limitationsFor(status,surface,missingRec){const limits=[];if(status==="FAIL")limits.push("Cannot promote this surface without either a better export or a human-provided mapping.");if((surface==="inventory"||surface==="due_in")&&missingRec.includes("as_of_date"))limits.push("Without a timestamp or snapshot date, AXM cannot prove when the state was true.");if(surface==="inventory"&&missingRec.includes("allocated_qty"))limits.push("Without allocation or reservation fields, on-hand quantity may overstate physical availability.");if(surface==="maintenance"&&missingRec.includes("required_part_id"))limits.push("Without required-part linkage, AXM may identify blocked work but not the supply constraint path.");if(surface==="claim_evidence")limits.push("This supports traceability, but it does not by itself prove the operational claim is true.");if(surface==="review")limits.push("Human review routes attention; it is not a machine truth verdict.");return limits}
function failSurface(surfaceType,tier,reason,limitations){return {sheet:null,status:"FAIL",surfaceType,evidenceTierCandidate:tier,passesAs:"",rowsCount:0,columnsDetected:[],canonicalFieldsDetected:[],missingMinimumGroups:[],missingRecommendedFields:[],reason,limitations}}

function parseDelimited(text,delimiter){const rows=[];let row=[],cell="",inQuotes=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&inQuotes&&next==='"'){cell+='"';i++;continue}if(ch==='"'){inQuotes=!inQuotes;continue}if(ch===delimiter&&!inQuotes){row.push(cell);cell="";continue}if((ch==="\n"||ch==="\r")&&!inQuotes){if(ch==="\r"&&next==="\n")i++;row.push(cell);rows.push(row);row=[];cell="";continue}cell+=ch}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows.filter(r=>r.some(x=>String(x).trim()))}
function detectJsonShape(obj){
  if(obj&&typeof obj==="object"&&!Array.isArray(obj)&&Array.isArray(obj.data)){const first=obj.data[0]||{},keys=first&&typeof first==="object"?Object.keys(first):[],probe=JSON.stringify(obj).slice(0,4000),looksOntology=keys.some(k=>["apiName","displayName","properties"].includes(k))||probe.includes("objectTypes");if(looksOntology)return {status:"PASS_WITH_GAPS",surfaceType:"ontology_or_api_capture",evidenceTierCandidate:"foundry_ontology_wire_shape_reconciled",passesAs:"Vendor-detached model/ontology capture candidate",rowsCount:obj.data.length,columnsDetected:keys.map(normalizeHeader),canonicalFieldsDetected:Object.keys(canonicalizeColumns(keys).reverse).sort(),missingMinimumGroups:[],missingRecommendedFields:["source_system","capture_time"],reason:"Recognized structured ontology/API list response.",limitations:["This preserves wire-shape structure and verbatim bytes; it does not prove live-tenant authority.","If the capture is partial, instance counts must be declared as partial, not hidden."]};return {status:"PASS_WITH_GAPS",surfaceType:"api_capture",evidenceTierCandidate:"api_list_capture",passesAs:"Structured API export candidate",rowsCount:obj.data.length,columnsDetected:keys.map(normalizeHeader),canonicalFieldsDetected:Object.keys(canonicalizeColumns(keys).reverse).sort(),missingMinimumGroups:[],missingRecommendedFields:["source_system","capture_time"],reason:"Recognized structured JSON list response.",limitations:["Needs source-system name and capture timestamp for stronger provenance."]}}
  if(Array.isArray(obj)&&obj.every(x=>x&&typeof x==="object"&&!Array.isArray(x))){const keys=Array.from(new Set(obj.slice(0,20).flatMap(x=>Object.keys(x)))),res=scoreTable(keys,obj.length);res.reason="Recognized JSON array of row-like objects. "+res.reason;res.records=obj.slice(0,5000).map((x,i)=>{const o={__row:i+1,__rowWord:"record"};for(const [k,v] of Object.entries(x))o[normalizeHeader(k)]=v;return o});return res}
  return {status:"PASS_WITH_GAPS",surfaceType:"raw_json_document",evidenceTierCandidate:"source_record",passesAs:"Verbatim source-evidence candidate",rowsCount:1,columnsDetected:[],canonicalFieldsDetected:[],missingMinimumGroups:[],missingRecommendedFields:["source_system","record_type"],reason:"JSON is valid but does not look like a known table or export shape.",limitations:["It can be retained as source evidence, but needs mapping to produce operational findings."]};
}

async function analyzeXlsx(file){
  try{if(typeof DecompressionStream==="undefined")return [failSurface("excel_workbook","xlsx_unreadable_in_this_browser","This browser cannot decompress XLSX files offline.",["Use a current Chrome or Edge browser, or export the sheet to CSV."])];const ab=await file.arrayBuffer(),zip=parseZip(new Uint8Array(ab)),entries={};for(const e of zip.entries)entries[e.name]=e;const sharedStrings=entries["xl/sharedStrings.xml"]?parseSharedStrings(await unzipEntry(zip.bytes,entries["xl/sharedStrings.xml"])):[],sheetNames={};if(entries["xl/workbook.xml"]&&entries["xl/_rels/workbook.xml.rels"])Object.assign(sheetNames,parseWorkbookSheetNames(await unzipEntry(zip.bytes,entries["xl/workbook.xml"]),await unzipEntry(zip.bytes,entries["xl/_rels/workbook.xml.rels"])));const sheetPaths=Object.keys(entries).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort(),surfaces=[];for(const path of sheetPaths){const allRows=parseWorksheet(textDecode(await unzipEntry(zip.bytes,entries[path])),sharedStrings),name=sheetNames[path]||path.replace("xl/worksheets/","").replace(".xml",""),picked=chooseHeaderAndRows(allRows,name),res=scoreTable(picked.headers,picked.dataRows.length,name);res.records=buildRecords(picked.headers,picked.dataRows,picked.headerIndex+2);res.headerRow=picked.headerIndex+1;surfaces.push({...res,sheet:name})}return surfaces.length?surfaces:[failSurface("excel_workbook","xlsx_no_worksheets","No worksheet XML files were found.",["Provide a standard XLSX workbook or export to CSV."])]}
  catch(err){return [failSurface("excel_workbook","xlsx_parse_failed","XLSX parse failed: "+err.message,["Export the relevant worksheet to CSV if the workbook uses unsupported compression or structure."])]}
}
function parseZip(bytes){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-66000);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error("ZIP end-of-central-directory not found");const count=dv.getUint16(eocd+10,true),cdOffset=dv.getUint32(eocd+16,true),entries=[];let off=cdOffset;for(let i=0;i<count;i++){if(dv.getUint32(off,true)!==0x02014b50)throw new Error("Invalid ZIP central directory");const method=dv.getUint16(off+10,true),compSize=dv.getUint32(off+20,true),uncompSize=dv.getUint32(off+24,true),nameLen=dv.getUint16(off+28,true),extraLen=dv.getUint16(off+30,true),commentLen=dv.getUint16(off+32,true),localOffset=dv.getUint32(off+42,true),name=new TextDecoder().decode(bytes.slice(off+46,off+46+nameLen));entries.push({name,method,compSize,uncompSize,localOffset});off+=46+nameLen+extraLen+commentLen}return {bytes,entries}}
async function unzipEntry(bytes,entry){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),off=entry.localOffset;if(dv.getUint32(off,true)!==0x04034b50)throw new Error("Invalid ZIP local header for "+entry.name);const nameLen=dv.getUint16(off+26,true),extraLen=dv.getUint16(off+28,true),dataStart=off+30+nameLen+extraLen,data=bytes.slice(dataStart,dataStart+entry.compSize);if(entry.method===0)return data;if(entry.method===8){const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream("deflate-raw"));return new Uint8Array(await new Response(stream).arrayBuffer())}throw new Error("Unsupported ZIP compression method "+entry.method+" for "+entry.name)}
function textDecode(bytes){return new TextDecoder("utf-8").decode(bytes)}
function xmlNodes(node,local){const ns=node.getElementsByTagNameNS?node.getElementsByTagNameNS("*",local):[];return ns&&ns.length?[...ns]:[...node.getElementsByTagName(local)]}
function xmlAttr(node,local){if(node.hasAttribute&&node.hasAttribute(local))return node.getAttribute(local);for(const a of [...(node.attributes||[])])if(a.localName===local||a.name===local)return a.value;return null}
function parseSharedStrings(bytes){const xml=new DOMParser().parseFromString(textDecode(bytes),"application/xml");return xmlNodes(xml,"si").map(si=>xmlNodes(si,"t").map(t=>t.textContent||"").join(""))}
function parseWorkbookSheetNames(wbBytes,relsBytes){const wb=new DOMParser().parseFromString(textDecode(wbBytes),"application/xml"),rels=new DOMParser().parseFromString(textDecode(relsBytes),"application/xml"),relMap={};for(const r of xmlNodes(rels,"Relationship")){let target=xmlAttr(r,"Target")||"";if(target.startsWith("/"))target=target.replace(/^\/+/,"");else target="xl/"+target.replace(/^\.?\//,"");relMap[xmlAttr(r,"Id")]=target}const out={};for(const sh of xmlNodes(wb,"sheet")){const name=xmlAttr(sh,"name"),rid=xmlAttr(sh,"id");if(name&&rid&&relMap[rid])out[relMap[rid]]=name}return out}
function parseWorksheet(xmlText,sharedStrings){const xml=new DOMParser().parseFromString(xmlText,"application/xml"),rows=[];for(const row of xmlNodes(xml,"row")){const arr=[];for(const c of xmlNodes(row,"c")){const ref=xmlAttr(c,"r")||"",col=colIndex(ref.replace(/[0-9]/g,""))||arr.length;arr[col]=readCell(c,sharedStrings)}if(arr.some(v=>String(v??"").trim()))rows.push(arr.map(v=>v??""))}return rows}
function readCell(c,sharedStrings){const t=xmlAttr(c,"t"),v=xmlNodes(c,"v")[0]?.textContent??"";if(t==="s")return sharedStrings[Number(v)]??v;if(t==="inlineStr")return xmlNodes(c,"t").map(x=>x.textContent||"").join("");if(t==="b")return v==="1"?"TRUE":"FALSE";return v}
function colIndex(letters){let n=0;for(const ch of letters.toUpperCase()){if(ch<"A"||ch>"Z")continue;n=n*26+(ch.charCodeAt(0)-64)}return n?n-1:0}
async function sha256File(file){const bytes=new Uint8Array(await file.arrayBuffer());if(window.crypto&&crypto.subtle&&crypto.subtle.digest){try{const hash=await crypto.subtle.digest("SHA-256",bytes);return hexBytes(new Uint8Array(hash))}catch(_e){}}return sha256Bytes(bytes)}
function hexBytes(bytes){return [...bytes].map(b=>b.toString(16).padStart(2,"0")).join("")}
