function toJsonReport(){return JSON.stringify({generatedAt:new Date().toISOString(),dataSource:state.isDemo?"built_in_dummy_data":"user_provided_local_files",findings:state.findings.map(f=>({kind:f.kind,label:SEV_META[f.kind].label,subject:f.subject,statement:f.statement,action:f.action||null,evidence:f.evidence.map(e=>({link:e.label,source:srcLabel(e.entry),where:rowRef(e.entry),sha256:e.entry.sha,record:e.text})),caveats:f.caveats,metrics:f.metrics})),surfaces:exportableResults()},null,2)}
function downloadBlob(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJson(){downloadBlob("axm_readiness_report.json",toJsonReport(),"application/json")}
function exportHtml(){const findings=$("findingView").innerHTML,summary=$("summaryView").innerHTML,table=$("surfaceTable").innerHTML,asks=$("asksView").outerHTML;const doc=`<!doctype html><html><head><meta charset="utf-8"><title>AXM Readiness Report</title><style>body{font-family:system-ui;max-width:1000px;margin:40px auto;padding:0 20px;color:#1c1b29;line-height:1.5}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ddd;text-align:left;vertical-align:top;font-size:12px}.finding{border:1px solid #ddd;border-left:4px solid #d94455;border-radius:10px;padding:16px;margin:14px 0}.fkind{font-size:11px;font-weight:700;text-transform:uppercase}.shiftact{background:#eef0fb;padding:10px;margin-top:10px}.summary{display:flex;gap:12px}.box{border:1px solid #ddd;padding:10px 16px}.box b{display:block;font-size:28px}.asks{padding:0;list-style:none}.asks li{border:1px solid #ddd;padding:10px;margin:8px 0}.chip,.st{font-size:10px;font-weight:700}.c-red,.fail{color:#d94455}.c-amber,.pass_with_gaps{color:#b87912}.c-green,.pass{color:#287a4a}</style></head><body><h1>AXM Readiness · Equipment Evidence</h1><p>${esc(new Date().toISOString())} · ${state.isDemo?"worked example, dummy data":"user-provided local files"}</p><h2>Finding</h2>${findings}<h2>Surface acceptance</h2>${summary}${table}<h2>What we need to get started</h2>${asks}<p style="margin-top:24px;font-size:12px;color:#666"><b>Honesty boundary:</b> intake readiness artifact, not a sealed shard.</p></body></html>`;downloadBlob("axm_readiness_report.html",doc,"text/html")}
function makeDemoFiles(){const files=[],add=(name,content,type)=>files.push(new File([content],name,{type:type||"text/plain"}));add("inventory_snapshot.csv",`niin,item_description,location,on_hand,serviceable_qty,allocated_qty,due_in_qty,as_of_date,source_record_id,notes
MPU-218,Mission processor unit,Depot-A/Bin-17,3,0,3,2,2026-03-31,INV-2026Q1-001,Administrative stock exists but none available for new work order
PUMP-441,Hydraulic pump,Depot-A/Bin-02,8,6,1,0,2026-03-31,INV-2026Q1-002,Available
SENSOR-104,Thermal sensor,ForwardShop-3,2,1,1,4,2026-03-31,INV-2026Q1-003,One serviceable and already allocated
`,"text/csv");add("maintenance_work_orders.csv",`jcn,tail_number,status,required_niin,nmcs_reason,opened_date,as_of_date,source_record_id,notes
WO-7001,ASSET-A17,NMCS_AWP,MPU-218,required part not serviceable or unallocated,2026-03-20,2026-03-31,MX-2026Q1-7001,Asset cannot return to service
WO-7002,ASSET-B22,open_scheduled,PUMP-441,,2026-03-18,2026-03-31,MX-2026Q1-7002,Awaiting shop capacity
WO-7003,ASSET-C08,open_diagnosis,SENSOR-104,repeat fault pending inspection,2026-03-27,2026-03-31,MX-2026Q1-7003,May become parts constraint
`,"text/csv");add("due_in_records.csv",`document_number,niin,quantity,status,edd,location,source_record_id,notes
REQ-9101,MPU-218,2,delayed,2026-04-14,Depot-A,DUEIN-9101,Late supplier shipment
REQ-9102,SENSOR-104,4,in_transit,2026-04-05,ForwardShop-3,DUEIN-9102,Expected before next maintenance cycle
`,"text/csv");add("bad_availability_export.csv",`description,notes
stuff exists somewhere,not enough fields to support availability
`,"text/csv");add("maintenance_shift_note.txt","Shift note 2026-03-31\nWO-7001 remains open. Required MPU-218 exists in stock count but no serviceable unallocated unit is available.\nSupply expects two units due 2026-04-14.\n","text/plain");return files}

document.addEventListener("DOMContentLoaded",init);
