function sha256Bytes(bytes){
  const K=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]);
  const bitLen=bytes.length*8,paddedLen=Math.ceil((bytes.length+9)/64)*64,data=new Uint8Array(paddedLen);data.set(bytes);data[bytes.length]=0x80;const dv=new DataView(data.buffer);dv.setUint32(paddedLen-8,Math.floor(bitLen/0x100000000),false);dv.setUint32(paddedLen-4,bitLen>>>0,false);
  let h0=0x6a09e667,h1=0xbb67ae85,h2=0x3c6ef372,h3=0xa54ff53a,h4=0x510e527f,h5=0x9b05688c,h6=0x1f83d9ab,h7=0x5be0cd19;const w=new Uint32Array(64),rotr=(x,n)=>(x>>>n)|(x<<(32-n));
  for(let off=0;off<paddedLen;off+=64){for(let i=0;i<16;i++)w[i]=dv.getUint32(off+i*4,false);for(let i=16;i<64;i++){const s0=rotr(w[i-15],7)^rotr(w[i-15],18)^(w[i-15]>>>3),s1=rotr(w[i-2],17)^rotr(w[i-2],19)^(w[i-2]>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let a=h0,b=h1,c=h2,d=h3,e=h4,f=h5,g=h6,h=h7;for(let i=0;i<64;i++){const S1=rotr(e,6)^rotr(e,11)^rotr(e,25),ch=(e&f)^((~e)&g),t1=(h+S1+ch+K[i]+w[i])>>>0,S0=rotr(a,2)^rotr(a,13)^rotr(a,22),maj=(a&b)^(a&c)^(b&c),t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}h0=(h0+a)>>>0;h1=(h1+b)>>>0;h2=(h2+c)>>>0;h3=(h3+d)>>>0;h4=(h4+e)>>>0;h5=(h5+f)>>>0;h6=(h6+g)>>>0;h7=(h7+h)>>>0}
  return [h0,h1,h2,h3,h4,h5,h6,h7].map(x=>x.toString(16).padStart(8,"0")).join("")
}
function imageDimensions(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const d={width:img.naturalWidth,height:img.naturalHeight};URL.revokeObjectURL(url);resolve(d)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("image load failed"))};img.src=url})}

function collectRows(results,type){const out=[];for(const r of results)for(const s of r.surfaces)if(s.status!=="FAIL"&&s.surfaceType===type&&Array.isArray(s.records))for(const rec of s.records)out.push({rec,s,file:r.fileName,sha:r.sha256});return out}
function fval(entry,canon){const key=(entry.s.fieldMap||{})[canon];return key?entry.rec[key]:undefined}
function rowRef(entry){const word=entry.rec.__rowWord||"row";return (entry.s.sheet?entry.s.sheet+" · ":"")+word+" "+entry.rec.__row}
function srcLabel(entry){return entry.file+(entry.s.sheet?" / "+entry.s.sheet:"")}
function surfaceCaveats(entries){const seen=new Set(),out=[];for(const e of entries){const miss=e.s.missingRecommendedFields||[];if(!miss.length)continue;const key=srcLabel(e)+"|"+miss.join(",");if(seen.has(key))continue;seen.add(key);out.push(`${e.s.surfaceType} surface “${srcLabel(e)}” lacks: ${miss.join(", ")} — confidence is limited accordingly.`)}return out}

function workCompleteness(w){let n=0;if(fval(w,"work_order_id"))n+=4;if(fval(w,"required_part_id"))n+=4;if(fval(w,"asset_id"))n+=2;if(fval(w,"status"))n+=2;if(fval(w,"blocking_reason"))n+=1;return n}

function buildFindings(results){
  const inv=collectRows(results,"inventory"),mx=collectRows(results,"maintenance"),due=collectRows(results,"due_in");
  if(!mx.length||!inv.length){const missing=[];if(!mx.length)missing.push("a maintenance or work-order surface (work order or asset ID, status, and ideally the required part)");if(!inv.length)missing.push("an inventory surface (item or part ID plus on-hand or serviceable quantity)");return {findings:[],note:"No cross-surface finding is possible yet. To test administrative availability against physical availability, AXM needs "+missing.join(" and ")+". That requirement is itself the first ask."}}
  const findings=[],seenWork=new Set();
  mx.sort((a,b)=>workCompleteness(b)-workCompleteness(a));
  for(const w of mx){const status=String(fval(w,"status")??"").toLowerCase();if(/closed|complete|completed|cancelled|canceled/.test(status))continue;const woId=String(fval(w,"work_order_id")??"").trim(),asset=String(fval(w,"asset_id")??"").trim(),reason=String(fval(w,"blocking_reason")??"").trim(),part=String(fval(w,"required_part_id")??"").trim(),workKey=woId?"WO:"+normId(woId):(asset&&part?"AP:"+normId(asset)+"|"+normId(part):"");if(workKey&&seenWork.has(workKey))continue;if(workKey)seenWork.add(workKey);const subject=asset?"Asset "+asset:(woId?"Work order "+woId:"An unidentified work order"),woLabel=woId?"work order "+woId:"an open work order";const evidence=[{label:"Work order",entry:w,text:[woId,asset,fval(w,"status"),reason?"reason: "+reason:""].filter(Boolean).join(" · ")}];
    if(!part){findings.push({kind:"no_part_link",subject,statement:`${subject} has ${woLabel} open (${fval(w,"status")??"status unknown"}), but the record carries no required-part linkage. It cannot be joined to inventory, so the supply constraint path is invisible.`,evidence,caveats:surfaceCaveats([w]),action:`Record the required part or NIIN on ${woLabel}, then resubmit the export.`,metrics:null});continue}
    const pid=normId(part),matches=inv.filter(x=>normId(fval(x,"item_id"))===pid),dueMatches=due.filter(d=>normId(fval(d,"item_id")??fval(d,"required_part_id"))===pid);let dueQty=null;const dueBits=[];for(const d of dueMatches){const q=toNum(fval(d,"quantity"));if(q!==null)dueQty=(dueQty??0)+q;dueBits.push([fval(d,"status"),fval(d,"due_date")?"EDD "+fval(d,"due_date"):""].filter(Boolean).join(", "));evidence.push({label:"Due-in",entry:d,text:[fval(d,"requisition_id"),fval(d,"quantity")!=null?"qty "+fval(d,"quantity"):"",fval(d,"status"),fval(d,"due_date")?"EDD "+fval(d,"due_date"):""].filter(Boolean).join(" · ")})}const dueTxt=dueMatches.length?`${dueQty??"Some"} due in — ${dueBits.filter(Boolean).join("; ")}.`:"No due-in record was provided for this part.";
    if(!matches.length){findings.push({kind:"no_inventory_match",subject,statement:`${subject} is waiting on ${part}${reason?" ("+reason+")":""}, but no inventory record for ${part} was found. The constraint cannot be tested against stock. ${dueTxt}`,evidence,caveats:surfaceCaveats([w,...dueMatches]),action:`Obtain an inventory export that covers ${part}, or confirm the part-ID mapping with supply.`,metrics:{part,onHand:null,serv:null,alloc:null,avail:null,dueQty}});continue}
    let onHand=null,serv=null,alloc=null;for(const m of matches){const oh=toNum(fval(m,"on_hand")),sv=toNum(fval(m,"serviceable_qty")),al=toNum(fval(m,"allocated_qty"));if(oh!==null)onHand=(onHand??0)+oh;if(sv!==null)serv=(serv??0)+sv;if(al!==null)alloc=(alloc??0)+al;evidence.splice(1,0,{label:"Inventory",entry:m,text:[part,oh!==null?"on hand "+oh:"",sv!==null?"serviceable "+sv:"",al!==null?"allocated "+al:"",fval(m,"location"),fval(m,"as_of_date")?"as of "+fval(m,"as_of_date"):""].filter(Boolean).join(" · ")})}
    const rawAvail=serv===null?null:serv-(alloc??0),avail=rawAvail===null?null:Math.max(0,rawAvail),involved=[w,...matches,...dueMatches],metrics={part,onHand,serv,alloc,avail,dueQty,inconsistentAllocation:rawAvail!==null&&rawAvail<0};
    if(avail===null)findings.push({kind:"unknown_availability",subject,statement:`${subject} is waiting on ${part}. Inventory shows ${onHand??"an unknown quantity"} on hand, but without serviceable and allocated fields, physical availability cannot be computed. The on-hand figure may overstate what can actually be issued. ${dueTxt}`,evidence,caveats:surfaceCaveats(involved),action:`Physically verify ${part} at the bin before planning against recorded stock, and capture serviceable and allocated counts in the next export.`,metrics});
    else if(avail<=0&&(onHand??0)>0)findings.push({kind:"masked_shortage",subject,statement:`${subject} is down, waiting on ${part}${reason?" ("+reason+")":""}. The record shows ${onHand} on hand, but ${serv??0} serviceable and ${alloc??0} allocated leave none physically available to this work${metrics.inconsistentAllocation?"; allocations exceed serviceable stock":""}. Administrative stock exists; issuable stock does not. ${dueTxt}`,evidence,caveats:surfaceCaveats(involved),action:`Do not plan this job against recorded on-hand stock. Ask supply whether an allocated unit of ${part} can be diverted, chase the due-in, and record the serviceable/unallocated split.`,metrics});
    else if(avail<=0)findings.push({kind:"shortage",subject,statement:`${subject} is waiting on ${part}, and the record confirms the shortage: ${onHand??0} on hand and ${avail} physically available. ${dueTxt}`,evidence,caveats:surfaceCaveats(involved),action:`Treat as parts-blocked. Chase the due-in for ${part} and record the EDD against the work order.`,metrics});
    else findings.push({kind:"supportable",subject,statement:`${subject} requires ${part}, and the record shows ${avail} unit(s) physically available (${serv} serviceable, ${alloc??0} allocated). Stock on record can support this work, if the record is true.`,evidence,caveats:surfaceCaveats(involved),action:`Issue ${part} against serviceable stock and update the allocation record when the unit is committed.`,metrics});
  }
  findings.sort((a,b)=>SEV_ORDER[a.kind]-SEV_ORDER[b.kind]);return findings.length?{findings,note:null}:{findings:[],note:"Maintenance and inventory surfaces were loaded, but no open work orders were found to test against stock."};
}

function surfaceCounts(results){const c={PASS:0,PASS_WITH_GAPS:0,FAIL:0};for(const r of results)for(const s of r.surfaces)c[s.status]=(c[s.status]||0)+1;return c}
