function renderAnatomy(){
  const o=organ();if(!o)return '<div class="empty">No organ selected.</div>';
  return `${renderHero(o)}
    <div class="grid two">
      <section class="card"><div class="card-head"><div><h2>Current anatomy</h2><p>Function, authority, and failure boundary remain separate from the current implementation and maintainer.</p></div></div>
        <div class="bar-list">${Object.entries(o.health||{}).map(([k,v])=>`<div class="barrow"><span>${esc(cap(k))}</span><div class="track"><div class="fill" style="width:${v*20}%"></div></div><code>${v}/5</code></div>`).join('')}</div>
      </section>
      <section class="card"><div class="card-head"><div><h2>Authority membrane</h2><p>The organ's power is defined by what it owns and what it is forbidden to decide.</p></div></div>
        <div class="grid two"><div><h3>Owns</h3><ul class="plain-list">${(o.authority?.owns||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h3>Forbidden</h3><ul class="plain-list">${(o.authority?.forbidden||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div>
      </section>
    </div>
    <div class="section-title"><div><h2>Estate anatomy</h2><p>Dependencies are directional. Ember lines identify critical seams with only one currently accepted provider or implementation.</p></div><div class="right"><button class="btn small" data-add-candidate="${esc(o.id)}">+ Candidate</button></div></div>
    <section class="card"><div class="organ-map">${renderMap()}</div></section>
    <div class="section-title"><div><h2>${esc(o.name)} function ledger</h2><p>Coverage is an explicit review input. It does not become truth through averaging.</p></div></div>
    <div class="detail-columns">
      <section class="card table-wrap"><table class="function-table"><thead><tr><th>Function</th><th>Criticality</th><th>Coverage</th></tr></thead><tbody>${(o.functions||[]).map(f=>`<tr><td><b>${esc(f.name)}</b><br><code>${esc(f.id)}</code></td><td>${f.criticality}/5</td><td class="scorecell">${f.coverage}/5<div class="mini-track"><i style="width:${f.coverage*20}%"></i></div></td></tr>`).join('')}</tbody></table></section>
      <section class="card"><div class="grid two"><div><h3>Inputs</h3><ul class="plain-list">${(o.inputs||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h3>Outputs</h3><ul class="plain-list">${(o.outputs||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div><h3 style="margin-top:1rem">Dependencies</h3>${(o.dependencies||[]).length?`<ul class="plain-list">${o.dependencies.map(d=>`<li><b>${esc(organ(d.target)?.name||d.target)}</b> · ${esc(d.kind)} · criticality ${d.criticality}/5 · replaceability ${d.replaceability}/5</li>`).join('')}</ul>`:'<div class="empty">No declared organ dependencies.</div>'}</section>
    </div>`;
}
function renderMap(){
  const organs=model.organs;const w=1000,h=430,cx=500,cy=215,r=Math.min(330,Math.max(220,organs.length*32));
  const pos={};organs.forEach((o,i)=>{const a=-Math.PI/2+i*(Math.PI*2/organs.length);pos[o.id]={x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*Math.min(r*.58,155)};});
  const edges=organs.flatMap(o=>(o.dependencies||[]).map(d=>({from:o.id,to:d.target,...d}))).filter(e=>pos[e.from]&&pos[e.to]);
  return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Estate organ dependency map"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"></path></marker></defs>${edges.map(e=>{const a=pos[e.from],b=pos[e.to];const critical=e.criticality>=4&&e.replaceability<=1;return `<path class="map-edge ${critical?'critical':''}" d="M ${a.x} ${a.y} Q ${cx} ${cy} ${b.x} ${b.y}" marker-end="url(#arrow)"></path>`}).join('')}${organs.map(o=>{const p=pos[o.id];return `<g class="map-node ${o.id===selectedOrganId?'selected':''}" data-map-organ="${esc(o.id)}" transform="translate(${p.x},${p.y})"><circle r="42"></circle><text text-anchor="middle" y="-2">${esc(o.name.slice(0,14))}</text><text class="subtext" text-anchor="middle" y="14">${esc(o.class)}</text></g>`}).join('')}</svg>`;
}
function renderEvolution(){
  const o=organ();const set=candidateSet();let c=candidate();if(!c||c.organId!==o.id){c=set[0];selectedCandidateId=c?.id;}
  return `${renderHero(o)}
    <div class="section-title"><div><h2>Evolution candidates</h2><p>Each proposal names what survives, what changes, who benefits, who validates, what evidence exists, and which hard gates remain open.</p></div><div class="right"><button class="btn small primary" data-add-candidate="${esc(o.id)}">+ Candidate</button></div></div>
    <div class="candidate-strip">${set.map(x=>{const p=posture(x);return `<button class="candidate ${x.id===selectedCandidateId?'active':''}" data-candidate="${esc(x.id)}"><span class="posture ${p.key}">${p.label}</span><b>${esc(x.name)}</b><p>${esc(x.summary)}</p><div class="candidate-foot"><span>${esc(x.action)}</span><span>${evidenceStrength(x).rows.length} receipts</span></div></button>`}).join('')||'<div class="empty">No candidates exist for this organ.</div>'}</div>
    ${c?renderCandidateEditor(c):''}
    <div class="section-title"><div><h2>Candidate comparison</h2><p>The table preserves the full fitness envelope. It deliberately avoids a single total score.</p></div></div>
    ${renderComparison(set)}`;
}
function renderCandidateEditor(c){
  const flags=candidateFlags(c);const p=posture(c);return `<div class="section-title"><div><h2>${esc(c.name)}</h2><p>${esc(c.summary)}</p></div><div class="right"><span class="tag ${p.key==='pass'?'green':p.key==='fail'?'red':'gold'}">${p.label}</span><button class="btn small danger" data-delete-candidate="${esc(c.id)}">Delete</button></div></div>
    <div class="editor-grid">
      <section class="card"><div class="card-head"><div><h3>Fitness envelope</h3><p>0 means absent or structurally unsafe. 5 means demonstrated strength inside the current scope.</p></div></div>${DIMENSIONS.map(([k,l])=>`<div class="slider-row"><label for="dim-${k}">${l}</label><input id="dim-${k}" type="range" min="0" max="5" step="1" value="${c.dimensions?.[k]??0}" data-dimension="${k}"><output>${c.dimensions?.[k]??0}</output></div>`).join('')}</section>
      <section class="card"><div class="card-head"><div><h3>Migration ledger</h3><p>A transition is incomplete until every preserved, changed, retired, and introduced object is named.</p></div></div>${['preserve','alter','retire','introduce'].map(k=>`<div class="field"><label>${cap(k)}</label><textarea class="textarea" data-change="${k}">${esc((c.changes?.[k]||[]).join('\n'))}</textarea></div>`).join('')}</section>
    </div>
    <div class="section-title"><div><h2>Hard gates</h2><p>Function and authority failures block the proposal. Open evidence or migration holds it outside a durable decision.</p></div></div>
    <div class="gate-grid">${GATES.map(([k,l])=>`<div class="gate" data-state="${esc(c.gates?.[k]||'open')}"><label>${l}</label><select data-gate="${k}">${['pass','warn','fail','open'].map(v=>`<option ${c.gates?.[k]===v?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}</div>
    <div class="section-title"><div><h2>Actor concentration</h2><p>Overlap is preserved as structure. The surface does not infer hidden motive from it.</p></div></div>
    <section class="card">${renderRoleGrid(c)}</section>
    <div class="section-title"><div><h2>Evidence links</h2><p>At least two load-bearing records, including one independent or external anchor, are required for an evidence-pass posture.</p></div></div>
    <section class="card"><div class="grid two">${model.evidence.map(e=>`<label class="scenario"><input type="checkbox" data-evidence-link="${esc(e.id)}" ${(c.evidenceIds||[]).includes(e.id)?'checked':''}><span><b>${esc(e.title)}</b><p>${esc(e.tier)} · ${esc(e.independence)} · ${esc(e.claim)}</p></span></label>`).join('')}</div></section>
    <div class="section-title"><div><h2>Structural findings</h2><p>These findings classify mechanisms and missing evidence. They are not allegations about intent.</p></div></div>
    <div class="flag-list">${flags.map(f=>`<div class="flag ${f.level==='high'?'high':f.level==='good'?'good':''}"><b>${esc(f.title)}</b><p>${esc(f.text)}</p></div>`).join('')}</div>`;
}
function renderRoleGrid(c){
  const roles=[['sponsors','Sponsor'],['validators','Validator'],['deciders','Decider'],['beneficiaries','Beneficiary']];
  return `<div class="role-grid"><div class="head">Actor</div>${roles.map(r=>`<div class="head">${r[1]}</div>`).join('')}${model.actors.map(a=>`<div><b>${esc(a.name)}</b><br><span class="hint">${esc((a.roles||[]).join(', '))}</span></div>${roles.map(([k])=>`<div><input type="checkbox" aria-label="${esc(a.name)} ${k}" data-actor-link="${k}" data-actor-id="${esc(a.id)}" ${(c.actorLinks?.[k]||[]).includes(a.id)?'checked':''}></div>`).join('')}`).join('')}</div>`;
}
function renderComparison(set){
  if(!set.length)return '<div class="empty">No candidates to compare.</div>';
  return `<section class="card table-wrap"><table class="compare-table"><thead><tr><th>Candidate</th><th>Posture</th>${DIMENSIONS.map(d=>`<th>${esc(d[1])}</th>`).join('')}<th>Evidence</th></tr></thead><tbody>${set.map(c=>{const p=posture(c),ev=evidenceStrength(c);return `<tr><td><b>${esc(c.name)}</b><br><code>${esc(c.action)}</code></td><td><span class="posture ${p.key}">${p.label}</span></td>${DIMENSIONS.map(([k])=>`<td class="scorecell">${c.dimensions?.[k]??0}<div class="mini-track"><i style="width:${(c.dimensions?.[k]??0)*20}%"></i></div></td>`).join('')}<td>${ev.rows.length} records<br><span class="hint">${Math.round(ev.value*100)}% weighted · ${ev.independent?'independent anchor':'no independent anchor'}</span></td></tr>`}).join('')}</tbody></table></section>`;
}
function renderActors(){
  const c=candidate()||candidateSet()[0];return `<section class="hero"><div class="hero-card"><div class="kicker">Motivation without mind-reading</div><h1>Actors, roles, interests, and authority</h1><p class="lead">The surface preserves self-declared, ascribed, and inferred interests as separate claims. It does not convert role overlap, status, funding, authorship, or disagreement into motive truth.</p><div class="control-line"><button class="btn primary" data-add-actor>+ Actor</button></div></div><div class="hero-card"><div class="metric-grid"><div class="metric"><strong>${model.actors.length}</strong><span>actors</span></div><div class="metric"><strong>${model.actors.flatMap(a=>a.interests||[]).length}</strong><span>interest claims</span></div><div class="metric warn"><strong>${model.actors.filter(a=>(a.interests||[]).some(i=>i.mode!=='self_declared')).length}</strong><span>ascribed or inferred</span></div><div class="metric"><strong>${c?actorConcentration(c)[0]?.roles.length||0:0}</strong><span>maximum candidate role overlap</span></div></div></div></section>
    <div class="grid two">${model.actors.map(a=>`<section class="card"><div class="card-head"><div><h2>${esc(a.name)}</h2><p>${esc((a.roles||[]).join(' · '))}</p></div><button class="btn small" data-edit-actor="${esc(a.id)}">Edit</button></div><h3>Authority</h3><ul class="plain-list">${(a.authority||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3 style="margin-top:1rem">Interest claims</h3><div class="flag-list">${(a.interests||[]).map(i=>`<div class="flag ${i.mode==='inferred'?'high':''}"><b>${esc(cap(i.mode))}</b><p>${esc(i.claim)}</p><p><i>${esc(i.evidence||'No evidence named.')}</i></p></div>`).join('')||'<div class="empty">No interest claims recorded.</div>'}</div></section>`).join('')}</div>
    <div class="section-title"><div><h2>Candidate role matrix</h2><p>Select a candidate in Evolution to change the active matrix. Concentration is a review trigger, not a verdict.</p></div></div>
    <section class="card">${c?renderRoleGrid(c):'<div class="empty">No candidate selected.</div>'}</section>`;
}
function renderEvidence(){
  const filters=['all','confirmed','measured','reported','derived','judgment','open'];return `<section class="hero"><div class="hero-card"><div class="kicker">Evidence ledger</div><h1>What supports the transition, and what remains open?</h1><p class="lead">A source can support a bounded claim without proving the proposal, the actor's intent, or the wisdom of the decision. Independence and limitations stay visible.</p><div class="control-line"><button class="btn primary" data-add-evidence>+ Evidence</button></div></div><div class="hero-card"><div class="metric-grid">${['confirmed','measured','reported','open'].map(t=>`<div class="metric"><strong>${model.evidence.filter(e=>e.tier===t).length}</strong><span>${t}</span></div>`).join('')}</div></div></section>
    <div class="section-title"><div><h2>Ledger</h2><p>Evidence classes are procedural. They do not become truth through quantity.</p></div><div class="right"><select id="evidenceFilter" class="select" style="width:170px">${filters.map(f=>`<option>${f}</option>`).join('')}</select></div></div>
    <div id="evidenceList" class="grid">${evidenceListHtml('all')}</div>
    <div class="section-title"><div><h2>Candidate sufficiency</h2><p>Weighted strength combines tier and independence only to expose review gaps. It is not a probability.</p></div></div>
    <section class="card table-wrap"><table class="compare-table"><thead><tr><th>Candidate</th><th>Records</th><th>Independent anchor</th><th>Weighted strength</th><th>Evidence gate</th></tr></thead><tbody>${model.candidates.map(c=>{const e=evidenceStrength(c);return `<tr><td>${esc(c.name)}</td><td>${e.rows.length}</td><td>${e.independent?'yes':'no'}</td><td>${Math.round(e.value*100)}%</td><td>${esc(c.gates?.evidence||'open')}</td></tr>`}).join('')}</tbody></table></section>`;
}
function evidenceListHtml(filter){
  return model.evidence.filter(e=>filter==='all'||e.tier===filter).map(e=>`<article class="evidence-card"><div><div class="evidence-tier">${esc(e.tier)}</div><small>${esc(e.independence)}</small></div><div><h3>${esc(e.title)}</h3><p><b>Claim:</b> ${esc(e.claim)}</p><p><b>Limits:</b> ${esc(e.limits)}</p><small>${esc(e.source)}</small></div><button class="btn small danger" data-delete-evidence="${esc(e.id)}">Delete</button></article>`).join('')||'<div class="empty">No evidence in this class.</div>';
}
function renderStress(){
  const set=candidateSet();return `<section class="hero"><div class="hero-card"><div class="kicker">Stress before mutation</div><h1>Test the organ under loss, load, capture, and succession</h1><p class="lead">A candidate should survive more than its preferred future. Select scenarios, then compare which weaknesses become material without collapsing the result into a single score.</p><div class="control-line"><button class="btn primary" id="runStressBtn">Run selected tests</button></div></div><div class="hero-card"><div class="metric-grid"><div class="metric"><strong>${model.scenarios.length}</strong><span>scenarios</span></div><div class="metric"><strong>${set.length}</strong><span>candidates in scope</span></div><div class="metric ${stressResults?'good':'warn'}"><strong>${stressResults?'ready':'open'}</strong><span>last run</span></div><div class="metric"><strong>${selectedOrganId.split('.').pop()}</strong><span>organ scope</span></div></div></div></section>
    <div class="section-title"><div><h2>Scenario set</h2><p>All tests are selected by default. Clear a test only when its operating condition is explicitly outside the decision horizon.</p></div></div>
    <div class="scenario-grid">${model.scenarios.map(s=>`<label class="scenario"><input type="checkbox" data-scenario="${esc(s.id)}" checked><span><b>${esc(s.name)}</b><p>${esc(s.description)}</p><div class="tagrow" style="margin-top:.4rem">${s.dimensions.map(d=>`<span class="tag">${esc(cap(d))}</span>`).join('')}</div></span></label>`).join('')}</div>
    <div class="section-title"><div><h2>Stress result</h2><p>Pass requires an average of 4 across the scenario's relevant dimensions. Warn begins at 2.5. A hard gate failure remains blocking regardless of this table.</p></div></div>
    <div id="stressResult">${stressResults?renderStressTable(stressResults):'<div class="empty">Run the selected scenarios to produce a candidate-by-scenario envelope.</div>'}</div>`;
}
function runStress(){
  const selected=[...document.querySelectorAll('[data-scenario]:checked')].map(x=>x.dataset.scenario);const scenarios=model.scenarios.filter(s=>selected.includes(s.id));const set=candidateSet();
  stressResults={organId:selectedOrganId,scenarios:scenarios.map(s=>({id:s.id,name:s.name,results:set.map(c=>{const n=avg(s.dimensions.map(d=>c.dimensions?.[d]??0));return {candidateId:c.id,value:n,state:n>=4?'pass':n>=2.5?'warn':'fail'};})}))};
  document.getElementById('stressResult').innerHTML=renderStressTable(stressResults);toast('Stress envelope updated.');
}
function renderStressTable(results){
  const set=candidateSet(results.organId);return `<section class="card table-wrap"><table class="stress-table"><thead><tr><th>Scenario</th>${set.map(c=>`<th>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${results.scenarios.map(s=>`<tr><td><b>${esc(s.name)}</b></td>${set.map(c=>{const r=s.results.find(x=>x.candidateId===c.id);return `<td class="result-${r.state}">${r.state.toUpperCase()} · ${r.value.toFixed(1)}/5</td>`}).join('')}</tr>`).join('')}</tbody></table></section>`;
}
function renderDecision(){
  const o=organ();const set=candidateSet();const eligible=set.filter(c=>posture(c).key==='pass');const chosen=candidate(model.decision?.candidateId)||eligible[0]||set[0];const memo=decisionMemo(o,chosen);
  return `<section class="hero"><div class="hero-card"><div class="kicker">Decision record</div><h1>Choose the transition without rewriting the anatomy</h1><p class="lead">The surface can classify eligibility, expose missing evidence, preserve dissent, and draft the record. A named authority still accepts, rejects, or holds the proposal.</p><div class="control-line"><button class="btn primary" id="exportMemoBtn">Export memorandum</button><button class="btn" id="exportCsvBtn">Export comparison CSV</button></div></div><div class="hero-card"><div class="metric-grid"><div class="metric good"><strong>${eligible.length}</strong><span>admissible candidates</span></div><div class="metric warn"><strong>${set.filter(c=>['warn','open'].includes(posture(c).key)).length}</strong><span>pilot or hold</span></div><div class="metric bad"><strong>${set.filter(c=>posture(c).key==='fail').length}</strong><span>blocked</span></div><div class="metric"><strong>${model.decision?.state||'open'}</strong><span>decision state</span></div></div></div></section>
    <div class="grid two"><section class="card"><div class="card-head"><div><h2>Decision controls</h2><p>Changing this form updates the local workspace. Export JSON to preserve the record.</p></div></div><div class="field"><label>Candidate</label><select id="decisionCandidate" class="select">${set.map(c=>`<option value="${esc(c.id)}" ${chosen?.id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>State</label><select id="decisionState" class="select">${['proposed','accepted','rejected','held','superseded','revoked'].map(v=>`<option ${model.decision?.state===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Decider</label><select id="decisionDecider" class="select">${model.actors.map(a=>`<option value="${esc(a.id)}" ${model.decision?.decider===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Rationale</label><textarea id="decisionRationale" class="textarea">${esc(model.decision?.rationale||'')}</textarea></div><div class="field"><label>Open questions · one per line</label><textarea id="decisionQuestions" class="textarea">${esc((model.decision?.openQuestions||[]).join('\n'))}</textarea></div><button class="btn primary" id="saveDecisionBtn">Update decision record</button></section><section class="card"><h2>Admissibility ledger</h2><div class="flag-list">${set.map(c=>{const p=posture(c),ev=evidenceStrength(c);return `<div class="flag ${p.key==='fail'?'high':p.key==='pass'?'good':''}"><b>${esc(c.name)} · ${p.label}</b><p>${Object.entries(c.gates||{}).map(([k,v])=>`${k}:${v}`).join(' · ')}</p><p>${ev.rows.length} evidence records; ${ev.independent?'independent anchor present':'no independent anchor'}.</p></div>`}).join('')}</div></section></div>
    <div class="section-title"><div><h2>Generated memorandum</h2><p>The draft classifies the object, names actors, explains the mechanism, carries receipts, widens the map, and ends with a control question.</p></div></div>
    <article class="memo" id="memo">${memo}</article>`;
}
function decisionMemo(o,c){
  if(!o||!c)return '<p>No organ and candidate are available.</p>';
  const p=posture(c),ev=evidenceStrength(c),flags=candidateFlags(c),decider=actor(model.decision?.decider);const sponsors=(c.actorLinks?.sponsors||[]).map(id=>actor(id)?.name||id);const validators=(c.actorLinks?.validators||[]).map(id=>actor(id)?.name||id);const beneficiaries=(c.actorLinks?.beneficiaries||[]).map(id=>actor(id)?.name||id);
  const strongest=DIMENSIONS.map(([k,l])=>[l,c.dimensions?.[k]??0]).sort((a,b)=>b[1]-a[1]).slice(0,3);const weakest=DIMENSIONS.map(([k,l])=>[l,c.dimensions?.[k]??0]).sort((a,b)=>a[1]-b[1]).slice(0,3);
  const question=model.decision?.openQuestions?.[0]||`Which function, authority, or obligation would become unrecoverable if ${c.name} were implemented and later removed?`;
  return `<h2>${esc(o.name)} organ evolution memorandum</h2><p><b>Classification.</b> ${esc(o.name)} is a ${esc(o.stage)} ${esc(o.class)} organ. The candidate <i>${esc(c.name)}</i> is currently classified as <b>${esc(p.label)}</b>. That classification comes from the explicit function, authority, evidence, migration, and reversibility gates. It does not establish that the proposal is wise, inevitable, or supported by every stakeholder.</p><p><b>Actors and mechanism.</b> Sponsors are ${esc(sponsors.join(', ')||'not named')}; validators are ${esc(validators.join(', ')||'not named')}; beneficiaries are ${esc(beneficiaries.join(', ')||'not named')}; the recorded decision authority is ${esc(decider?.name||'unassigned')}. The proposed mechanism is to ${esc(c.action.replaceAll('_',' '))} the organ while preserving ${esc((c.changes?.preserve||[]).join('; ')||'no preserved objects yet named')}, changing ${esc((c.changes?.alter||[]).join('; ')||'no changes yet named')}, retiring ${esc((c.changes?.retire||[]).join('; ')||'nothing currently named')}, and introducing ${esc((c.changes?.introduce||[]).join('; ')||'nothing currently named')}.</p><p><b>Receipts and limits.</b> The candidate cites ${ev.rows.length} evidence record(s), with weighted review strength ${Math.round(ev.value*100)} percent and ${ev.independent?'an independent anchor':'no independent anchor'}. Its strongest declared dimensions are ${esc(strongest.map(x=>`${x[0]} ${x[1]}/5`).join(', '))}; its weakest are ${esc(weakest.map(x=>`${x[0]} ${x[1]}/5`).join(', '))}. The principal structural findings are ${esc(flags.map(f=>f.title).join('; '))}. Those findings classify the evidence and control geometry. They do not prove hidden motivation, causation, capability outside the measured scope, or wrongdoing.</p><p><b>Wider map.</b> The decision affects ${esc((o.outputs||[]).join(', ')||'no outputs named')}, depends on ${esc((o.dependencies||[]).map(d=>organ(d.target)?.name||d.target).join(', ')||'no other organs')}, and must preserve the authority membrane that owns ${esc((o.authority?.owns||[]).join(', '))} while refusing ${esc((o.authority?.forbidden||[]).join(', '))}. A legitimate evolution must also survive steward exit, supplier loss, load growth, capture attempts, relicensing, network loss, and institutional fork without erasing ancestry or handing accepted authority to an implementation supplier.</p><p><b>Decision state.</b> ${esc(model.decision?.rationale||'No rationale has been recorded.')}</p><p><b>Control question.</b> ${esc(question)}</p><div class="receipt">format: axm-organ-evolution/1\nestate: ${esc(model.estate.id)}\norgan: ${esc(o.id)}\ncandidate: ${esc(c.id)}\nposture: ${esc(p.label)}\ndecision: ${esc(model.decision?.state||'proposed')}\ndecider: ${esc(model.decision?.decider||'unassigned')}\nevidence_records: ${ev.rows.length}\nindependent_anchor: ${ev.independent}</div>`;
}
