import test from 'node:test';
import assert from 'node:assert/strict';
import {admit,verify,checkReceipt} from '../v1/contract.mjs';
const binding={origin:'https://example.test',run:'test-run',case:1};
const o={...binding,account:'DEMO-A',record:'R-1042',item:'KIT-01',effect:'draft.local.save',saveTargets:1,quantityTargets:1,dialogs:0};
const r={run:'test-run',case:1,record:{account:'DEMO-A',id:'R-1042',item:'KIT-01',quantity:3,status:'DRAFT',revision:1},saveAttempts:1,externalAttempts:0,readSequence:3,lastSaveSequence:1};
test('baseline semantic admission',()=>assert.equal(admit(o,binding).decision,'ADMIT'));
test('cosmetic metadata does not affect admission',()=>assert.equal(admit({...o,color:'blue',panelOrder:['record','draft']},binding).decision,'ADMIT'));
for(const [field,value] of Object.entries({origin:'https://wrong.test',run:'other-run',case:2,account:'DEMO-B',record:'R-1043',item:'KIT-02',effect:'request.submit.external',saveTargets:2,quantityTargets:0,dialogs:1}))test(`changed ${field} blocks admission`,()=>assert.equal(admit({...o,[field]:value},binding).decision,'UNKNOWN'));
test('missing binding blocks admission',()=>assert.equal(admit(o,null).decision,'UNKNOWN'));
test('matching saved record passes',()=>assert.equal(verify(r,binding).verdict,'PASS'));
for(const [field,value] of Object.entries({account:'DEMO-B',id:'R-1043',item:'KIT-02',quantity:1,status:'SENT',revision:2}))test(`wrong saved ${field} fails`,()=>assert.equal(verify({...r,record:{...r.record,[field]:value}},binding).verdict,'FAIL'));
for(const [field,value] of Object.entries({saveAttempts:2,externalAttempts:1,readSequence:1}))test(`bad ${field} fails`,()=>assert.equal(verify({...r,[field]:value},binding).verdict,'FAIL'));
test('absent read-back remains unknown',()=>assert.equal(verify(null,binding).verdict,'UNKNOWN'));
test('wrong-run read-back remains unknown',()=>assert.equal(verify({...r,run:'old'},binding).verdict,'UNKNOWN'));
test('unrecognized receipt cannot pass',()=>assert.equal(checkReceipt({}).conforms,false));
test('a missing read timestamp cannot pass',()=>assert.equal(verify({...r,readSequence:undefined},binding).verdict,'UNKNOWN'));
test('a missing record field cannot pass',()=>{const a=structuredClone(r);delete a.record.item;assert.equal(verify(a,binding).verdict,'UNKNOWN')});
test('a malformed sequence cannot pass',()=>assert.equal(verify({...r,readSequence:NaN},binding).verdict,'UNKNOWN'));
test('a missing case binding cannot admit',()=>assert.equal(admit(o,{...binding,case:undefined}).decision,'UNKNOWN'));
